### ISSUE TITLE
web_log should use correct metrics type

### ISSUE THREAD

**Issue by Wing924** [netdata/go.d.plugin#130]
resp_time is not counter, it should use gauge.

ref. netdata/netdata#3907

**Comment by ilyam8** [comment]
found
https://github.com/netdata/netdata/pull/1758#issuecomment-279150948

> I think the web_log plugin has an major issue. You are passing all metrics as absolute.

**Comment by Wing924** [comment]
@ilyam8 
I'm talking about golang's version
https://github.com/netdata/go.d.plugin/blob/master/modules/weblog/charts.go#L80-L82

**Comment by ilyam8** [comment]
Same. Netdata does interpolation for `incremental` values and shows `absolute` as-is, so incremental i always preferable

@ktsaou

**Comment by Wing924** [comment]
@ilyam8 

> Same. Netdata does interpolation for `incremental` values and shows `absolute` as-is, so incremental i always preferable

It's not true. You can check netdata/netdata#3907 and found what's wrong.
