### ISSUE TITLE
Error with apache plugin

### ISSUE THREAD

**Issue by glennie** [netdata/go.d.plugin#151]
Hi, 
I've activated apache go plugin.
The charts didn't show up and I've go the following error:
"error on parsing status : unknown value : Using GnuTLS version"

My apache.conf config is:

>{
  "jobs": [
    {
      "name": "apache",
      "url": "http://127.0.0.1/server-status?auto"
    }
  ]
}

Please note that the configuration file is valid (tested with yamllint).

The error is triggered by some fields from the apache status page which should not be parsed by the plugin.

Apache status handler output:

> [glennie@nemesis /etc/netdata/go.d]$ curl http://127.0.0.1/server-status?auto
127.0.0.1
ServerVersion: Apache/2.4.37 (Debian) mod_gnutls/0.8.4 GnuTLS/3.6.5 mod_wsgi/4.5.17 Python/2.7 mod_perl/2.0.10 Perl/v5.28.1
ServerMPM: prefork
Server Built: 2018-11-03T13:26:31
CurrentTime: Sunday, 17-Feb-2019 11:55:10 CET
RestartTime: Sunday, 17-Feb-2019 00:01:25 CET
ParentServerConfigGeneration: 1
ParentServerMPMGeneration: 0
ServerUptimeSeconds: 42825
ServerUptime: 11 hours 53 minutes 45 seconds
Load1: 0.18
Load5: 0.11
Load15: 0.17
Total Accesses: 17922
Total kBytes: 155278
Total Duration: 8668354
CPUUser: 1013.56
CPUSystem: 115.62
CPUChildrenUser: 16.48
CPUChildrenSystem: 2.37
CPULoad: 2.68075
Uptime: 42825
ReqPerSec: .418494
BytesPerSec: 3712.89
BytesPerReq: 8872.04
DurationPerReq: 483.671
BusyWorkers: 1
IdleWorkers: 9
Scoreboard: _____W.____...........................................................................................................................................
Using GnuTLS version: 3.6.5
Built against GnuTLS version: 3.5.19

Disabling libapache2-mod-gnutls module makes go.d apache work properly (as the last two lines are not printed by the apache status handler).

IMHO, the apache go plugin must ignore unknown fields from the output.

Kind regards,

PS: thank you all for these fantastic piece of software.

**Comment by ilyam8** [comment]
@glennie thanks for reporting!
