### ISSUE TITLE
springboot2 feature: add uri filters

### ISSUE THREAD

**Issue by ntlug** [netdata/go.d.plugin#189]
Right now the springboot2 modules which depends on prometheus metrics doesn't take any parameters.  I suggest a yaml parameter be added that can be a list of regexp patterns to exclude uri's from the metrics responses (so that actuator, etc.) can be filtered.  Maybe the parm would be called filter_uri_regexp (which is a yaml list of regexps)?

Bonus if you enable both a filter (remove) and a set (only do for specified uri's).

I'm tempted to fork and attempt, but I'm not a "go" expert... so not sure if I'd do things in the most efficient manner.

The reason for this feature, right now the response counts count all bad, unknown, and actuator endpoints... and you might be interested only in the counts for your custom endpoints.

**Comment by ilyam8** [comment]
Hi @ntlug !

@Wing924

**Comment by ilyam8** [comment]
> Bonus if you enable both a filter (remove) and a set (only do for specified uri's).
> I'm tempted to fork and attempt, but I'm not a "go" expert... so not sure if I'd do things in the most efficient manner.

i've talked to @Wing924, he said the request is ok and he will look at it next week, probably on Monday.

**Comment by ntlug** [comment]
Thanks, would mean the world to us.  In Springboot 1.x it wasn't as big of a issue.  But now, we're on SB 2.x and we really need this one.  Thanks again.

**Comment by ilyam8** [comment]
@ntlug 

> Bonus if you enable both a filter (remove) and a set (only do for specified uri's).

I think `filter_uri` will be enough if we use simple pattern as filter

https://docs.netdata.cloud/libnetdata/simple_pattern/#netdata-simple-patterns

`allowThis* !denyThat *`

what do you think?

**Comment by ntlug** [comment]
Do simple patterns allow for any kind of pattern matching? (e.g. globbing)  Was hoping for regex really.

**Comment by Wing924** [comment]
I think this matcher is better: <https://github.com/netdata/go.d.plugin/blob/master/pkg/matcher/README.md>

example:
```yml
- name: mysb
   uri_filter:
    includes:
    - ~ ^/myapp/ # regexp matches 
    - * */assert/*    # glob matches
    excludes:
    - ~ *.ignore$ # regexp matches
    - = /healthcheck # string compare with ==
```

**Comment by ilyam8** [comment]
> Do simple patterns allow for any kind of pattern matching? 

see `man 7 glob`

> Was hoping for regex really.

Then we need 2 options

**Comment by ntlug** [comment]
And of course, define (document) the ordering of the application of includes/excludes (just so it's clear)

**Comment by ilyam8** [comment]
https://github.com/netdata/go.d.plugin/issues/189#issuecomment-480455834

it is hard to understand what `uri` will pass the filter - a lot of includes and excludes, really error prone.

**Comment by ilyam8** [comment]
Just saying, if you guys are ok with it @ntlug @Wing924 i am ok too :smile:

**Comment by ntlug** [comment]
That's way I like a regex.  You know what the prometheus uri's look like and so a regex person knows what do to.  Just need to define the ordering.  Since the default ordering is "all allow" starting with that should help define how you want to document the ordering.

**Comment by ilyam8** [comment]
@ntlug 

Hm, i think there is no ordering. URI passes if:
 - it matches by any of matchers in `includes`
 - it doesnt match by any of matcher in `excludes`

@Wing924 right?

**Comment by Wing924** [comment]
Yes, it equals to
`(uri =~ includes[0] || uri =~ includes[1] || ...) && (uri !~ excludes[0] || uri !~ excludes[1] || ...)`
where `=~` means match (string, regexp, glob or simple pattern)

**Comment by ntlug** [comment]
I know it sounds weird, but you just gave an ordering :)

**Comment by Wing924** [comment]
order is for shortcut evaluate :)
