### ISSUE TITLE
Does netdata-updater get latest go.d commits?

### ISSUE THREAD

**Issue by ntlug** [netdata/go.d.plugin#211]
Like the subject says.  Is there a way to update the go.d plugin from latest nightly yet?

**Comment by ilyam8** [comment]
Hi @ntlug sorry for the late response.

> Does netdata-updater get latest go.d commits

No, netdata installer downloads [latest release](https://github.com/netdata/go.d.plugin/releases).

The bad thing about it that installer doesn't verify existence of go.d.plugin and it's version, it always downloads and installs specific version (which is hardcoded).

So if you compile latest go.d.plugin from source and put it under `plugins.d` intaller will overwrite it with _stable_ version.

This should be fixed imo.

___

i release new version every 2 weeks, if there is some bug i always can do bugfix release asap.
