### ISSUE TITLE
[BUG?] httpcheck global setting 'update_every' doesn't work?

### ISSUE THREAD

**Issue by weijing24** [netdata/go.d.plugin#237]
hi, 
recently I use a go.d.plugin called httpcheck and It's really awesome. But I find a problem. I don't know if this is a bug or just my wrong config. Here is my detail information.

### system information:
ubuntu 16.04.6
netdata v1.15.0-105-g8a1a437e
docker-ce 18.09.6 

### my netdata httpcheck config
go.d/httpcheck.conf
```
update_every        : 15
autodetection_retry : 3
priority            : 70000
jobs:
  - name: netdata-com
    url: https://netdata.cloud/
    status_accepted: [200]
    timeout: 2
  - name: baidu-com
    url: https://www.baidu.com
    update_every: 20
```

### What's my problem
As you can see, I set global update_every to 15s, I capture all packages from my netdata container. According to my understanding, my netdata container will httpcheck netdata.cloud(216.239.38.21) every 15s, httpcheck baidu.com(61.135.169.121) every 20s.It looks that **global setting doesn't work** just JOB configuration really works.
![image](https://user-images.githubusercontent.com/8737314/60339518-98165a00-99db-11e9-8b3f-37961bb6e20f.png)
![image](https://user-images.githubusercontent.com/8737314/60339483-7cab4f00-99db-11e9-856e-82bd68920c0e.png)

It's so wired. Is this a bug or just I config httpcheck.conf wrong? Can anyone help me solve this?

### Expected results
httpcheck netdata.cloud every 15s

**Comment by ilyam8** [comment]
hey @weijing24 	

Yes, this is the bug, global params are not respected if defaults are set.

`UpdateEvery` is set for `httpcheck`, so the only way to overwrite it is to set per job `update_every`.

https://github.com/netdata/go.d.plugin/blob/08373322e7cef033103d305b127ba925b5e1bf08/modules/httpcheck/httpcheck.go#L15-L17


___

thx for reporting, i will fix it

**Comment by ilyam8** [comment]
(nice avatar btw)

**Comment by weijing24** [comment]
Thank you for your prompt reply

**Comment by weijing24** [comment]
@ilyam8 
I'm sorry to bother you. I still find global setting doesn't work in latest netdata image. And I think found the reason. 
here is my /etc/netdata/netdata.conf
```
[global]
        history = 7200
        update every = 30
```
here is my /etc/netdata/go.d/httpcheck.conf
```
update_every        : 15
autodetection_retry : 3
priority            : 70000
jobs:
 - name: "netdata"
   url: https://netdata.cloud/
   status_accepted: [200]
   timeout: 2
```
Accoring to the config above, I found netdata httpcheck netdata.cloud every 30s not 15s.
Can you help me resolve my confusion？
- Should netdata.conf's  `update every = 30` be prior to httpcheck.conf's `update_every        : 15`?
- Is it a bug or netata's design philosophy(netdata.conf's global setting prior to any plugin's global setting)?

**Comment by ilyam8** [comment]
> I'm sorry to bother you. I still find global setting doesn't work in latest netdata image.

yes, you are right, latest netdata image includes go.d.plugin 0.7.0, fixes will be in  the next go.d.plugin release (0.8.0) - on Sunday or Monday (very likely)

**Comment by ilyam8** [comment]
> here is my /etc/netdata/netdata.conf

[global]
        history = 7200
        update every = 30

`update every` under `global` section is **minumum** update every. So it can be higher, but not lower.

**Comment by weijing24** [comment]
@ilyam8 got it, thank you very much :smile:
