### ISSUE TITLE
Processing time chart per URL not working

### ISSUE THREAD

**Issue by jmorais** [netdata/go.d.plugin#243]
Timings chart per URL is not getting any data even though the full timings chart is.

![Screen Shot 2019-07-22 at 3 03 16 PM](https://user-images.githubusercontent.com/556684/61657867-088a6100-ac92-11e9-9377-40ec4bd7f943.png)

What could be the problem?

**Comment by ilyam8** [comment]
go version of web_log under big refactor (#141), i wouldn recomment to use it for now, because it is very likely there will be some breaking changes. I recommend to use python version (it has no per url charts feature, but same can be achieved using filters i think).
