### ISSUE TITLE
scaleio: per storage pool/sdc metrics 

### ISSUE THREAD

**Issue by Egyras** [netdata/go.d.plugin#256]
There is no multiple storage pool data - how much capacity In-Use, total capacity for each pool. 

value - netdata_scaleio_system_workload_primary_bandwidth_KB_persec_average for **write** shows negative values instead positive.

**Comment by ilyam8** [comment]
@Egyras i wont be able to look into it until next week

**Comment by Egyras** [comment]
@ilyam8 I believe in the code there is mutiply by -1 for **all write** values, I dont think that this is required:

{ID: "system_backend_primary_bandwidth_write", Name: "write", Mul: -1, Div: 1000},

**Comment by ilyam8** [comment]
@Egyras oh, this is on purpose. Use `data=as-collected` option.

https://docs.netdata.cloud/backends/prometheus/#netdata-data-source

**Comment by ilyam8** [comment]
> There is no multiple storage pool data - how much capacity In-Use, total capacity for each pool.

Current implementation provides only summary metrics. We could get same metrics per protection domain/storage pool/device. 

So you are saying we need total/in-use per storage pool?

**Comment by Egyras** [comment]
> There is no multiple storage pool data - how much capacity In-Use, total capacity for each pool.
> 
> Current implementation provides only summary metrics. We could get same metrics per protection domain/storage pool/device.
> So you are saying we need total/in-use per storage pool?

Its better to make per storage pool as option because it makes more sense if we do capacity monitoring. We can have multiple storage pools and it consists of different SDS and for example alert is generated when you reach storage pool set limit.

Also I dont see any latency metrics, SclaeIO (VxflexOS) API has such metrics under SDS:
/api/types/Device/instances/action/querySelectedStatistics
avgReadLatencyInMicrosec
avgWriteLatencyInMicrosec

**Comment by ilyam8** [comment]
> under SDS

As you see there is only `System` section in [the request](https://github.com/netdata/go.d.plugin/blob/master/modules/scaleio/queries.go)

My goal was to add all info from the main page of the dashboard. 

> Its better to make per storage pool as option because it makes more sense if we do capacity monitoring.

We can get huge amount of metrics via API, i am waiting for real use cases, it was not clear for me which metrics are needed (not a `scaleio` user).

Ofc i am open to suggestion and i agree that we need whatever is needed.

**Comment by ilyam8** [comment]
So, @Egyras what do you need exactly? Storage pool capacity?

**Comment by Egyras** [comment]
@ilyam8
Would be nice to have each storage pool capacity, pools Total Capacity (I believe its maxCapacityInKb from API) and Capacity In-Use (from API capacityInUseInKb)

**Comment by ilyam8** [comment]
it will take me some time to create a lab, i will try to setup it this weekend

**Comment by Egyras** [comment]
@ilyam8 
In new 3.0.1 ver there is a few new counters under /api/types/Sdc/instances/action/querySelectedStatistics
most usefull for troubleshooting would be:

userDataSdcReadLatency Bwc object
userDataSdcWriteLatency Bwc object

**Comment by ilyam8** [comment]
please post here the whole response, i will compare it with v2 (the only version i have) response

**Comment by Egyras** [comment]
> please post here the whole response, i will compare it with v2 (the only version i have) response

@ilyam8  Its new counters which apeared in 3.0.1 ver.

**Comment by ilyam8** [comment]
I know i know, but are they the only new counters?

And some counters can be removed in v3 comp to v2.

If i include in req some counters that dont exist the request will fail.

**Comment by Egyras** [comment]
@ilyam8 as I know just added new, old ones still exists

**Comment by ilyam8** [comment]
ok, i asked because of

> https://github.com/netdata/netdata/issues/6475

**Comment by ilyam8** [comment]
ive prepared `scaleIO` lab, will be working on it next sprint (finally 😅)

**Comment by Egyras** [comment]
@ilyam8  great news, ping me if you have issues as I have ScaleIO in my LAB as well.

**Comment by ilyam8** [comment]
Perfect. I am no v2.6.1.1_113, so ofc i will need your help to get it working on both versions.

@spiegela any chance you can send me updated binaries?

**Comment by spiegela** [comment]
Yes! Sorry for the delay getting back with you. I’ll get you the updated binaries ASAP, and email you privately.

**Comment by ilyam8** [comment]
@Egyras 

List of available statistics for `/api/instances/querySelectedStatistics` call

- `Sdc`

<details>
<summary>click!</summary>

```
'numOfMappedVolumes',
 'userDataReadBwc',
 'userDataWriteBwc',
 'volumeIds'
```

</details>

- `StoragePool`

<details>
<summary>click!</summary>

```
'BackgroundScanCompareCount',
 'BackgroundScannedInMB',
 'activeBckRebuildCapacityInKb',
 'activeFwdRebuildCapacityInKb',
 'activeMovingCapacityInKb',
 'activeMovingInBckRebuildJobs',
 'activeMovingInFwdRebuildJobs',
 'activeMovingInNormRebuildJobs',
 'activeMovingInRebalanceJobs',
 'activeMovingOutBckRebuildJobs',
 'activeMovingOutFwdRebuildJobs',
 'activeMovingOutNormRebuildJobs',
 'activeMovingRebalanceJobs',
 'activeNormRebuildCapacityInKb',
 'activeRebalanceCapacityInKb',
 'atRestCapacityInKb',
 'bckRebuildCapacityInKb',
 'bckRebuildReadBwc',
 'bckRebuildWriteBwc',
 'capacityAvailableForVolumeAllocationInKb',
 'capacityInUseInKb',
 'capacityLimitInKb',
 'degradedFailedCapacityInKb',
 'degradedFailedVacInKb',
 'degradedHealthyCapacityInKb',
 'degradedHealthyVacInKb',
 'deviceIds',
 'failedCapacityInKb',
 'failedVacInKb',
 'fixedReadErrorCount',
 'fwdRebuildCapacityInKb',
 'fwdRebuildReadBwc',
 'fwdRebuildWriteBwc',
 'inMaintenanceCapacityInKb',
 'inMaintenanceVacInKb',
 'inUseVacInKb',
 'maxCapacityInKb',
 'movingCapacityInKb',
 'normRebuildCapacityInKb',
 'normRebuildReadBwc',
 'normRebuildWriteBwc',
 'numOfDevices',
 'numOfMappedToAllVolumes',
 'numOfSnapshots',
 'numOfThickBaseVolumes',
 'numOfThinBaseVolumes',
 'numOfUnmappedVolumes',
 'numOfVolumes',
 'numOfVolumesInDeletion',
 'numOfVtrees',
 'pendingBckRebuildCapacityInKb',
 'pendingFwdRebuildCapacityInKb',
 'pendingMovingCapacityInKb',
 'pendingMovingInBckRebuildJobs',
 'pendingMovingInFwdRebuildJobs',
 'pendingMovingInNormRebuildJobs',
 'pendingMovingInRebalanceJobs',
 'pendingMovingOutBckRebuildJobs',
 'pendingMovingOutFwdRebuildJobs',
 'pendingMovingOutNormrebuildJobs',
 'pendingMovingRebalanceJobs',
 'pendingNormRebuildCapacityInKb',
 'pendingRebalanceCapacityInKb',
 'primaryReadBwc',
 'primaryReadFromDevBwc',
 'primaryReadFromRmcacheBwc',
 'primaryVacInKb',
 'primaryWriteBwc',
 'protectedCapacityInKb',
 'protectedVacInKb',
 'rebalanceCapacityInKb',
 'rebalanceReadBwc',
 'rebalanceWriteBwc',
 'rfacheReadHit',
 'rfacheWriteHit',
 'rfcacheAvgReadTime',
 'rfcacheAvgWriteTime',
 'rfcacheIoErrors',
 'rfcacheIosOutstanding',
 'rfcacheIosSkipped',
 'rfcacheReadMiss',
 'rfcacheReadsFromCache',
 'rfcacheReadsPending',
 'rfcacheReadsReceived',
 'rfcacheReadsSkipped',
 'rfcacheReadsSkippedAlignedSizeTooLarge',
 'rfcacheReadsSkippedHeavyLoad',
 'rfcacheReadsSkippedInternalError',
 'rfcacheReadsSkippedLockIos',
 'rfcacheReadsSkippedLowResources',
 'rfcacheReadsSkippedMaxIoSize',
 'rfcacheReadsSkippedStuckIo',
 'rfcacheSkippedUnlinedWrite',
 'rfcacheSourceDeviceReads',
 'rfcacheSourceDeviceWrites',
 'rfcacheWriteMiss',
 'rfcacheWritePending',
 'rfcacheWritesReceived',
 'rfcacheWritesSkippedCacheMiss',
 'rfcacheWritesSkippedHeavyLoad',
 'rfcacheWritesSkippedInternalError',
 'rfcacheWritesSkippedLowResources',
 'rfcacheWritesSkippedMaxIoSize',
 'rfcacheWritesSkippedStuckIo',
 'rmPendingAllocatedInKb',
 'secondaryReadBwc',
 'secondaryReadFromDevBwc',
 'secondaryReadFromRmcacheBwc',
 'secondaryVacInKb',
 'secondaryWriteBwc',
 'semiProtectedCapacityInKb',
 'semiProtectedVacInKb',
 'snapCapacityInUseInKb',
 'snapCapacityInUseOccupiedInKb',
 'spareCapacityInKb',
 'thickCapacityInUseInKb',
 'thinCapacityAllocatedInKb',
 'thinCapacityInUseInKb',
 'totalReadBwc',
 'totalWriteBwc',
 'unreachableUnusedCapacityInKb',
 'unusedCapacityInKb',
 'userDataReadBwc',
 'userDataWriteBwc',
 'volumeIds',
 'vtreeIds'
```

</details>



___

For `Sdc` there is no options, we will use  'userDataReadBwc' and 'userDataWriteBwc'.

What about `StoragePool`?

**Comment by ilyam8** [comment]
@Egyras i m almost finished

New charts
> https://github.com/ilyam8/go.d.plugin/tree/scaleio_sdc_sp_metrics/modules/scaleio#charts

Details
> https://github.com/ilyam8/go.d.plugin/blob/scaleio_sdc_sp_metrics/modules/scaleio/charts.go

Will be merged in a few days
