### ISSUE TITLE
x509check missing smtp (starttls) support

### ISSUE THREAD

**Issue by Kraeutergarten** [netdata/go.d.plugin#258]
Currently x509check isn't able to check smtp certificates, cause of missing starttls command.

**Comment by ilyam8** [comment]
Hi @Kraeutergarten, indeed, you are right. I am not a specialist and i have no smtp server to test. I googled for the solution, i think we need something like this:

```go
	c, err := smtp.Dial("smtp.srv:465")
	if err != nil {
		log.Fatal(err)
	}
	err = c.StartTLS(nil)
	if err != nil {
		log.Fatal(err)
	}
	v ,ok := c.TLSConnectionState()
	if !ok {
		return
	}
	_ = v.PeerCertificates
```

It is not clear how to understand that it is smtp by address, i dont want to add an option to explicitly point that we need smtp cert getter. Do you have any ideas?

**Comment by ilyam8** [comment]
We could use `smtp` scheme 🤔 Like

> smtp://x.x.x.x:yy

**Comment by ncovercash** [comment]
Hey,

I'm not sure if this is part of the same issue, but it seemed close enough to prevent me creating a new one and I saw no other related issues that were more relevant.

When testing now, even with a known-good server like smtp.gmail.com:587. I get the following error:
```
collect.go:12 error on dial to 'tcp:///smtp.gmail.com:587': dial tcp: missing address
```

Again, this might be the wrong place, but it seemed most applicable.

**Comment by ilyam8** [comment]
Hi

https://github.com/netdata/go.d.plugin/blob/6542eefdc8697a4c8fc1060e620d4ff13575c44d/config/go.d/x509check.conf#L131-L132


should be `smtp://smtp.my_mail.org:587`

https://github.com/netdata/go.d.plugin/commit/9725cd71efbbb018496b36742cf27958a76d3be2
