### ISSUE TITLE
Vsphere, Collecting metric works, but not graph

### ISSUE THREAD

**Issue by BenoitPoulet** [netdata/go.d.plugin#273]
Hello,

I'm trying to setup the new external plugin in Go for vsphere, without success.

The plugin seems to works but nothing about vsphere is shown in the Netdata UI.

Netdata v1.17.1 (rpm from EPEL)
go.d.plugin, version: v0.10.0

Traces from the Go binary execution
```
...
[ INFO  ] vsphere[pirv-vctr] discover.go:74 discovering : discovered 3/3 hosts, 8/37 vms, the whole process took 103.468403ms
[ INFO  ] vsphere[pirv-vctr] discover.go:11 starting discovery process, will do discovery every 5m0s
[ INFO  ] main[main] start.go:46 vsphere[pirv-vctr]: autodetection success
[ DEBUG ] main[main] orchestrator.go:141 tick 0
[ DEBUG ] vsphere[pirv-vctr] collect.go:11 starting collection process
[ DEBUG ] vsphere[pirv-vctr] scrape.go:48 scraping : scraped metrics for 3/3 hosts, process took 19.084715ms
[ DEBUG ] vsphere[pirv-vctr] scrape.go:60 scraping : scraped metrics for 8/8 vms, process took 30.10192ms
[ DEBUG ] vsphere[pirv-vctr] collect.go:23 metrics collected, process took 49.839793ms
CHART 'netdata.execution_time_of_vsphere_pirv-vctr' '' 'Execution Time for vsphere_pirv-vctr' 'ms' 'go.d' 'netdata.go_plugin_execution_time' '' '145000' '20' '' 'go.d' 'vsphere'
DIMENSION 'time' '' '' '' '' ''

CHART 'vsphere_pirv-vctr.host-21_cpu_usage_total' '' 'Cpu Usage Total' 'percentage' 'host pir-5520-esxi-02.services.com' 'vsphere.cpu_usage_total' 'area' '70000' '20' '' 'go.d' 'vsphere'
DIMENSION 'host-21_cpu.usage.average' 'used' '' '' '100' ''

BEGIN vsphere_pirv-vctr.host-21_cpu_usage_total
SET host-21_cpu.usage.average = 283
END
....
```
Any idea ?

Regards.

**Comment by ilyam8** [comment]
@BenoitPoulet 

Did you run the plugin in debug mode as `netdata` user?

Anyway it should work. Correct place to go and check for problems is `error.log`, plese do

> grep vsphere `error.log`

**Comment by ilyam8** [comment]
Probably you need to wait a bit after netdata service start (up to 20s by default). Try to refresh dashboard after 20s.

**Comment by BenoitPoulet** [comment]
Yes, i did an "su - netdata -s /bin/bash", and i run the process with the following command line :
```bash-4.2$ ./go.d.plugin-v0.10.0.linux-amd64  -c /etc/netdata/conf.d/ ```

Absolutely no reference to "vsphere" in /var/log/netdata/*

**Comment by ilyam8** [comment]
ok, please do

 - cp /dev/null error.log
 - restart netdata.service
 - wait 20s
 - `grep "go.d" error.log`

share grep output

**Comment by ilyam8** [comment]
> ./go.d.plugin-v0.10.0.linux-amd64 -c /etc/netdata/conf.d/

oh, where did you get `go.d.plugin-v0.10.0.linux-amd64`, it should be `go.d.plugin`

you can find it in `plugins.d` dir

**Comment by BenoitPoulet** [comment]
there is no "go.d.plugin" file in the RPM distributed by EPEL. :
```
[root@dirv-monitoring-centreon-01:netdata]find /  -type f -name go.d.plugin
[root@dirv-monitoring-centreon-01:netdata]rpm -ql netdata | grep go.d.plugin
[root@dirv-monitoring-centreon-01:netdata]
```
So i took the binary here : https://github.com/netdata/go.d.plugin/releases
And the config files by doing a check out of this Git.
I did a copy of "/home/go.d.plugin-master/config/" in /etc/netdata/conf.d/, and i edited the config file of the vsphere module.
```
[root@dirv-monitoring-centreon-01:netdata]grep "go.d" error.log
```
=> no result.

**Comment by ilyam8** [comment]
ok, change `go.d.plugin-v0.10.0.linux-amd64` name to `go.d.plugin`

**Comment by ilyam8** [comment]
And move it to `plugins.d` directory

```
test@debian10:~$ ls /opt/netdata/usr/libexec/netdata/plugins.d/
acl.sh                   cgroup-network             loopsleepms.sh.inc
alarm-email.sh           cgroup-network-helper.sh   node.d.plugin
alarm-notify.sh          charts.d.dryrun-helper.sh  perf.plugin
alarm.sh                 charts.d.plugin            python.d.plugin
alarm-test.sh            fping.plugin               request.sh
anonymous-statistics.sh  go.d.plugin                slabinfo.plugin
apps.plugin              health-cmdapi-test.sh      system-info.sh
cgroup-name.sh           ioping.plugin              tc-qos-helper.sh
```

**Comment by ilyam8** [comment]
> there is no "go.d.plugin" file in the RPM distributed by EPEL. :

cc: @paulkatsoulakis

**Comment by BenoitPoulet** [comment]
Perfect it works @ilyam8 !
I did what you said + i was forced to move the "god.d" directory and the "go.d.conf" under /etc/netdata :  
```
-bash-4.2$ ll /etc/netdata/
total 140
drwxr-xr-x 6 root root   4096 25 sept. 17:08 conf.d
drwxr-xr-x 2 root root   4096 25 sept. 15:53 go.d
-rw-r--r-- 1 root root    818 25 sept. 15:16 go.d.conf
-rw-r--r-- 1 root root 130074  4 juin  17:05 netdata.conf
```
I stopped the process a launched by hand, and i restarted the netdata service.
Now the graph are shown !!

Thanks a lot for you assistance @ilyam8
