### ISSUE TITLE
wmi via wmi_exporter, memory not present?

### ISSUE THREAD

**Issue by ntlug** [netdata/go.d.plugin#281]
I recently enabled wmi and even with  ENABLED_COLLECTORS="cpu,memory,net,logical_disk,os,system" 

And even though the promethus raw data seems to see memory related stuff:
wmi_cs_physical_memory_bytes 1.7179328512e+10
wmi_os_physical_memory_free_bytes 1.3940477952e+10
wmi_os_process_memory_limix_bytes 1.40737488224256e+14
wmi_os_virtual_memory_bytes 1.9729465344e+10
wmi_os_virtual_memory_free_bytes 1.622519808e+10
wmi_os_visible_memory_bytes 1.7179328512e+10

I don't see a collector area for it in prometheus.  Did something change?  Am I working off old documentatoin?

**Comment by ilyam8** [comment]
hi @ntlug 

> I don't see a collector area for it in prometheus

What is collector are in prometheus?

All you need is to run wmi exporter witn

> --collectors.enabled="cpu,memory,net,logical_disk,os,system"

option

wmi netdata modules collects `wmi_memory_*` data

https://github.com/netdata/go.d.plugin/blob/d802c68b8c8f93f2e699427639f616298a29774c/modules/wmi/collect_memory.go#L12-L43

**Comment by ilyam8** [comment]
See `collection` section, it contains 2 charts and there you can see all enabled modules

https://github.com/netdata/go.d.plugin/blob/d802c68b8c8f93f2e699427639f616298a29774c/modules/wmi/charts.go#L35-L54

**Comment by ntlug** [comment]
I don't get any of those metrics via the prometheus data.  Maybe because it's a VM??

wmi_exporter was started with "memory" as one of the collectors.

**Comment by ilyam8** [comment]
Well, i was using win10 vm writing this collector. It worked.

So if you go directly to the `:9182/metrics` there is no `wmi_memory_*` metrics?

Probably it is worth to ask wmi exporter guys

> https://github.com/martinlindhe/wmi_exporter/issues/new

**Comment by ilyam8** [comment]
@ntlug 

> --collectors.enabled="cpu,memory,net,logical_disk,os,system"

Do all other collectors work?

**Comment by ntlug** [comment]
yes.  And doing get-wmiobject win32_perfrawdata_perfos_memory returns stuff on the Windows 10 host directly.  Sigh.  Not sure why I can see the memory stuff.

 ```
get-wmiObject Win32_PerfRawData_PerfOS_Memory


__GENUS                              : 2
__CLASS                              : Win32_PerfRawData_PerfOS_Memory
__SUPERCLASS                         : Win32_PerfRawData
__DYNASTY                            : CIM_StatisticalInformation
__RELPATH                            : Win32_PerfRawData_PerfOS_Memory=@
__PROPERTY_COUNT                     : 46
__DERIVATION                         : {Win32_PerfRawData, Win32_Perf, CIM_StatisticalInformation}
__SERVER                             : CCOXW10EVAL
__NAMESPACE                          : root\cimv2
__PATH                               : \\CCOXW10EVAL\root\cimv2:Win32_PerfRawData_PerfOS_Memory=@
AvailableBytes                       : 13468061696
AvailableKBytes                      : 13152404
AvailableMBytes                      : 12844
CacheBytes                           : 188383232
CacheBytesPeak                       : 294903808
CacheFaultsPersec                    : 7624619
Caption                              : 
CommitLimit                          : 19729465344
CommittedBytes                       : 4011798528
DemandZeroFaultsPersec               : 53261382
Description                          : 
FreeAndZeroPageListBytes             : 6757175296
FreeSystemPageTableEntries           : 12554475
Frequency_Object                     : 0
Frequency_PerfTime                   : 10000000
Frequency_Sys100NS                   : 10000000
LongTermAverageStandbyCacheLifetimes : 14400
ModifiedPageListBytes                : 131682304
Name                                 : 
PageFaultsPersec                     : 94783070
PageReadsPersec                      : 313793
PagesInputPersec                     : 2080919
PagesOutputPersec                    : 0
PagesPersec                          : 2080919
PageWritesPersec                     : 0
PercentCommittedBytesInUse           : 873340618
PercentCommittedBytesInUse_Base      : 4294967295
PoolNonpagedAllocs                   : 0
PoolNonpagedBytes                    : 167051264
PoolPagedAllocs                      : 0
PoolPagedBytes                       : 409686016
PoolPagedResidentBytes               : 368037888
StandbyCacheCoreBytes                : 198610944
StandbyCacheNormalPriorityBytes      : 2102734848
StandbyCacheReserveBytes             : 4409540608
SystemCacheResidentBytes             : 188383232
SystemCodeResidentBytes              : 0
SystemCodeTotalBytes                 : 0
SystemDriverResidentBytes            : 9007104
SystemDriverTotalBytes               : 17936384
Timestamp_Object                     : 0
Timestamp_PerfTime                   : 1814654179591
Timestamp_Sys100NS                   : 132157148272920000
TransitionFaultsPersec               : 34222382
TransitionPagesRePurposedPersec      : 0
WriteCopiesPersec                    : 2324418
PSComputerName                       : CCOXW10EVAL
```

**Comment by ilyam8** [comment]
What version of wmi_exporter do you use?
if latest i suggest to check prev

> https://github.com/martinlindhe/wmi_exporter/releases/tag/v0.8.3

**Comment by ntlug** [comment]
I'll try it.  I think it may well be a bug in wmi_exporter.  I set enable the memory collector, but it's like it's not enabled.

**Comment by ntlug** [comment]
Nevermind.  I fat fingered it.  All is well, sorry.... user error.
