### ISSUE TITLE
go.d weblog README is empty

### ISSUE THREAD

**Issue by OdysLam** [netdata/go.d.plugin#286]
Hey, 

The README is empty, resulting in an [empty page](https://docs.netdata.cloud/collectors/go.d.plugin/modules/weblog/) in docs.netdata.

I think It should either be a clone of web_log python.d plugin, if the two plugins are identical in functionality, or omitted in the docs until the plugin is finished.

Thanks for your time :)

Best,
Odys

**Comment by ilyam8** [comment]
Will be added in https://github.com/netdata/go.d.plugin/pull/141

current go web_log is not good, new version will be replacement for python version

#141 almost finished

**Comment by OdysLam** [comment]
Thanks @ilyam8, maybe we could mention that in the readme so it is reflected in the docs.

Something along the lines of:

"plugin is WIP and will be released soon, please refer to python version (Link) untill the new version"

If the plugin is around the corner, it would be unnecessary ( I think).

In any case I am closing the issue.

Thanks :)
