### ISSUE TITLE
ScaleIO plugin not all metrics in prometheus db

### ISSUE THREAD

**Issue by Egyras** [netdata/go.d.plugin#299]
Why storage pool metrics are not exposed for prometheus ?

**Comment by Egyras** [comment]
Or maybe available docker image not updated yet ?

**Comment by ilyam8** [comment]
Yes, it is merged but i need to release new version of `go.d.plugin`. My plan to do it today.

**Comment by ilyam8** [comment]
@Egyras i need to fix #298 first (working atm), then i release new version

**Comment by ilyam8** [comment]
@Egyras 
https://github.com/netdata/netdata/pull/7418
