### ISSUE TITLE
Bring your own downsized Go.D.Plugin 

### ISSUE THREAD

**Issue by mapl** [netdata/go.d.plugin#302]
I am asking about a possible performance “feature” request.

As more and more support for additional collectors will be added (yea!) to the already large (normal for statically linked single binaries) go.d.plugin, the binary size will increase. 

For single board computers (raspberry pi, etc) or microcontroller with memory constraints, this could be indeed a potential problem!

To mitigate this, we could enable selective builds where you specify the collectors you need. As a result, you will have a tailored go.d.plugin with the smallest possible size!

Inspired by https://www.influxdata.com/blog/bring-your-own-telegraf/

**Comment by ilyam8** [comment]
>  the binary size will increase.

Yeah, [vsphere](https://github.com/netdata/go.d.plugin/tree/master/modules/vsphere) contributes *a lot* to the size (almost half).

**Comment by ilyam8** [comment]
Related:

https://github.com/upx/upx

```cmd
ilyam@debian-s-1vcpu-1gb-fra1-01:~/upx-3.96-amd64_linux$ ls -lh go.d*
-rwxr-x--- 1 root root  22M Jun 28 00:18 go.d.plugin
-rwxr-x--- 1 root root 5.6M Jun 27 21:26 go.d.plugin_packed

time ./go.d.plugin -h
real  0m0.015s
user  0m0.004s
sys   0m0.008s
time ./go.d.plugin_packed -h
real  0m0.211s
user  0m0.156s
sys   0m0.036s

```

**Comment by georgeok** [comment]
UPX is a good idea but keep in mind when you run the executable it decompressed it which results to the same RAM requirements as the original uncompressed executable. So it only solves the disk size problem not the memory.
 
One way we can do is by splitting the imported modules into multiple files and then using build tags pass by environment variables we can exclude specific modules from the final product. I did a [demo implementation here](https://github.com/georgeok/go.d.plugin/commit/4fd7676846da3458ca7965589f8403c616162645). For example
```
EXCLUDED_MODULES="vsphere mongodb" make build
``` 
will exclude vshere and mongodb from the final product saving around 18mb.

**Comment by ilyam8** [comment]
@georgeok I think RAM usage is another problem and we should investigate/profile/optimize code. This issue is about the size of the executable.

I did some tests and `upx` does really good job: 28M -> 5,1M.

```cmd
[ilyam@pc upx-3.96-amd64_linux]$ ls -lh godplugin
-rwxr-xr-x 1 ilyam ilyam 28M сен 16 10:31 godplugin
[ilyam@pc upx-3.96-amd64_linux]$ ./upx q --brute godplugin
                       Ultimate Packer for eXecutables
                          Copyright (C) 1996 - 2020
UPX 3.96        Markus Oberhumer, Laszlo Molnar & John Reiser   Jan 23rd 2020

        File size         Ratio      Format      Name
   --------------------   ------   -----------   -----------
upx: q: FileNotFoundException: q: No such file or directory
  28610560 ->   5344648   18.68%   linux/amd64   godplugin

Packed 1 file.
[ilyam@pc upx-3.96-amd64_linux]$ ls -lh godplugin
-rwxr-xr-x 1 ilyam ilyam 5,1M сен 16 10:31 godplugin
```

A downside of using it is it takes more time to start the plugin (uncompress and load into memory), but that is not crucial in my opinion (at least now).

Likely there are other problems I am not aware of.

---

> using build tags pass by environment variables we can exclude specific modules from the final product.

That is a very nice idea and I think we need to implement it! I will check how other projects do that.

**Comment by vkalintiris** [comment]
IIRC, another "drawback" of upx is that you need the executable pages to be writable as well.
