### ISSUE TITLE
Enable More request methods for go.d/web_log

### ISSUE THREAD

**Issue by Steve8291** [netdata/go.d.plugin#313]
If I enable one of my apache sites with the `%r` option in the go.d/web_log.conf it fails due to no support for the request methods of: MKCOL PROPFIND MOVE SEARCH
```
    log_type: csv
    csv_config:
      format: '- - - - - [%h] - \"%r\" %>s'
```
error.log:
> go.d WARNING: web_log[my_website] check failed: parse last line: csv parse: assign 'PROPFIND' : bad req method ([Mon Dec 30 13:40:47 2019] [xxx.xx.xx] - "PROPFIND /remote.php/dav/files/user/ HTTP/1.1" 207 "-" "Mozilla/5.0 mirall/2.3.3 (build 84) (my_website)" [-])

> go.d ERROR: web_log[my_website] Check failed

Would it be possible to enable these other request types or at least ignore them so that web_log can start for that site? However, the majority of requests to my site are "PROPFIND" so I'm not sure ignoring is the best option.
The two files that seem to be involved are:
master/modules/weblog/logline.go
master/modules/weblog/logline_test.go

**Comment by ilyam8** [comment]
Hi @Steve8291 

i updated `isReqMethodValid` func in #314

**Comment by ilyam8** [comment]
> [%h]

doesnt seem [a know field](https://github.com/netdata/go.d.plugin/tree/master/modules/weblog#known-fields), module skips it during collecion. You dont have `Current Poll Unique Clients` chart, do you?

> 

use `%h`

Module uses the field to chart ipv4/ipv6 unique clients

https://github.com/netdata/go.d.plugin/blob/79e076722c3bbb19b832ff3fcc221627abc30899/modules/weblog/collect.go#L117-L129

So it is not that important if it is `[ipv4]` or `ipv4`

**Comment by Steve8291** [comment]
Thanks @ilyam8 
I'm currently on: `netdata v1.19.0-219-nightly`
Just tested and It's not working yet so I think maybe that update hasn't been pulled down for me. Since the go.d plugin gets compiled I'm not sure how to check if my code has changed for it.
I'll wait a day and test again. 
Running in debug I can see you are right, I get a line:
`[ DEBUG ] web_log[status] init.go:31 skipping URL patterns creating, no patterns provided`
However, if I remove the brackets on `%h` Netdata fails and I get: (I removed ip address)
`go.d WARNING: web_log[netdata] check failed: verify last line: verify '[xxx.xxx.x.x]': bad req client `
If I escape the brackets it seems to fix the problem: `\[%h\]` and the WARNING goes away but I still do not see a `Current Poll Unique Clients` Chart on any of my other hosts.


My original Apache virtual host log format is:
`LogFormat "[%{%a %b %d %H:%M:%S %Y}t] [%h] %u \"%r\" %>s \"%{Referer}i\" \"%{User-Agent}i\" [%L]" accesslogs`

My full web_log.conf jobs section for that host is now:
```
  - name: my_site
    path: /var/log/apache2/my_site-access.log
    log_type: csv
    csv_config:
      format: '- - - - - \[%h\] - \"%r\" %>s'
      fields_per_record: -1
      trim_leading_space: no
```

**Comment by ilyam8** [comment]
> Just tested and It's not working yet so I think maybe that update hasn't been pulled down for me. 

Yes, the fix will be in the next [release](https://github.com/netdata/go.d.plugin/releases).

> However, if I remove the brackets on %h Netdata fails and I get: (I removed ip address)
go.d WARNING: web_log[netdata] check failed: verify last line: verify '[xxx.xxx.x.x]': bad req client

> Since the go.d plugin gets compiled I'm not sure how to check if my code has changed for it.

You could compile it yourself (you need to install `go` v1.13+).

 - git clone https://github.com/netdata/go.d.plugin
 - cd go.d.plugin
 - make

Chek `go.d.plugin/bin/` dir, there you will find `godplugin`. Repace current binary with the compiled one (change name to `go.d.plugin`). But keep in mind that it will be overwritted on the next update.
 
___

Yes, you right, it fails during verify

https://github.com/netdata/go.d.plugin/blob/89a72fddbec3f5aea91873de37bf2c174ff9b37f/modules/weblog/logline.go#L458

You have two options:
 - skip %h
 - use regexp parser

**Comment by Steve8291** [comment]
I think it would just be easier for me to remove the `[ ]` on my apache virtual host .conf file. That way I don't have to deal with a slower regex match. It would be nice to be able to escape other characters in the netdata config though. Thanks again for figuring all that out for me.

**Comment by ilyam8** [comment]
@Steve8291 latest version of plugin contains the fix

https://github.com/netdata/netdata/pull/7666
