### ISSUE TITLE
MySQL module permissions

### ISSUE THREAD

**Issue by softserbia** [netdata/go.d.plugin#323]
Docs should specify required permissions for the user which is specified in configuration, maybe even the example, like python plugin is https://docs.netdata.cloud/collectors/python.d.plugin/mysql/

I assume `USAGE, REPLICATION CLIENT` should be enough?

**Comment by ilyam8** [comment]
Hi @softserbia 

> Docs should specify required permissions for the user which is specified in configuration

> I assume USAGE, REPLICATION CLIENT should be enough?


Yes and yes 😄
