### ISSUE TITLE
Freeradius module incorrectly decodes 'access-rejects' and 'proxy-access-rejects' attributes

### ISSUE THREAD

**Issue by jpparker** [netdata/go.d.plugin#337]
The function `decodeServerResponse` in "modules/freeradius/freeradius.go" incorrectly uses `FreeRADIUSTotalAccessRequests_Get` and `FreeRADIUSTotalProxyAccessRequests_Get` for decoding 'access-rejects' and 'proxy-access-rejects', where there are dictionary functions written for this purpose.

**Comment by ilyam8** [comment]
fixed in #338 

thx @jpparker 😄

**Comment by ilyam8** [comment]
Fix will be in the new version in 2 days, i want to finish vernemq module before the release.

If you want to have the fix today i suggest to build the plugin from source. (use `make`)
