### ISSUE TITLE
cannot run the custom plugin

### ISSUE THREAD

**Issue by yasharne** [netdata/go.d.plugin#367]
Hi
I'm trying to run my own plugin written in go, I compiled the plugins without problem:
```
╰─$ make                                                                                                                                          2 ↵
go mod download
go vet ./...
go test ./... -race -cover -covermode=atomic
//test outputs
rm -rf bin
hack/go-build.sh
Building binaries for version: v0.18.0-6-g62e45e4-dirty
Building for os/arch linux/amd64
```
then I enabled my plugin in `/opt/netdata/etc/netdata/go.d.conf`:
```
enabled: yes
default_run: yes
max_procs: 0
modules:
  myplugin: yes
```
and the configuration inside `/opt/netdata/etc/netdata/go.d/myplugin.conf`:
```
jobs:
  - name: snapp
    source: snapp.taxi
```
but when I run the plugin in the debug mode I get this error:
```
netdata@user:~/usr/libexec/netdata/plugins.d$ ./go.d.plugin -d -m myplugin
[ CRIT  ] main[main] setup.go:83 no modules to run
```
In the code, I have registered my plugin:
```
func init() {
	creator := module.Creator{
		Defaults: module.Defaults{
			UpdateEvery: 60,
		},
		Create: func() module.Module { return New() },
	}

	module.Register("myplugin", creator)
}
```
I'm not sure if it is related or not but I don't have unit test for my code right now.
The output of `go.d.plugin -v`:
```
go.d.plugin, version: v0.18.0-6-g62e45e4-dirty
```

**Comment by ilyam8** [comment]
Hi @yasharne 

See https://github.com/netdata/go.d.plugin#developing

have you done 2nd step?

**Comment by ilyam8** [comment]
btw if your update every is 60 i suggest to add `store_first` option to the charts

> https://github.com/netdata/go.d.plugin/blob/62e45e4415a3752dd2a096581754e77b82f54f48/modules/pulsar/charts.go#L64

**Comment by ilyam8** [comment]
And keep in mind that go.d.plugin will be rewritten when new version is out

If you need custom i suggesto to make it standalone.

Example

https://github.com/netdata/go-orchestrator/blob/master/examples/simple/main.go

**Comment by yasharne** [comment]
@ilyam8 Thanks for your reply, I realized I've missed adding my plugin to the main.go file. fixed now
