### ISSUE TITLE
dns_query log spamming

### ISSUE THREAD

**Issue by tete1030** [netdata/go.d.plugin#372]
I'm using dns_query to monitor dns connection conditions. My connection to dns servers is not very well, so it often timed out when using tcp or tcp-tls. This causes tons of error log messages, which may cover up other real problems.

I'm proposing to downgrade these messages to 'debug' level and give user an option to disable dns_query logs that are not critical.

![image](https://user-images.githubusercontent.com/4312115/79710286-21927200-82f7-11ea-8de2-cf705922f8e1.png)

**Comment by ilyam8** [comment]
@tete1030 👋 

> these messages to 'debug' level

i think it is ok, will do

**Comment by tete1030** [comment]
Thanks! 😄
