### ISSUE TITLE
vcsa 

### ISSUE THREAD

**Issue by Jolin-blank** [netdata/go.d.plugin#375]
Post https://192.168.111.101/rest/com/vmware/cis/session: x509: cannot validate certificate for 192.168.111.101 because it doesn't contain any IP SANs

**Comment by ilyam8** [comment]
hi @Jolin-blank 

try to add `tls_skip_verify: no` to the job config

**Comment by Jolin-blank** [comment]
It doesn't work

**Comment by Jolin-blank** [comment]
> hi @Jolin-blank
> 
> try to add `tls_skip_verify: no` to the job config

It doesn't work

**Comment by ilyam8** [comment]
@Jolin-blank 

could you show your `vcsa.conf` ?

**Comment by Jolin-blank** [comment]
jolin_blank@163.com
 
From: Ilya Mashchenko
Date: 2020-04-28 16:22
To: netdata/go.d.plugin
CC: Jolin-blank; Mention
Subject: Re: [netdata/go.d.plugin] vcsa (#375)
@Jolin-blank
could you show your vcsa.conf ?
