### ISSUE TITLE
path to go.d.conf in freebsd

### ISSUE THREAD

**Issue by lklemo** [netdata/go.d.plugin#383]
i was trying to run the unbound plugin and in debug mode i found this warning.
there is double /usr/ in the path

[ WARN  ] main[main] setup.go:52 find config file error : can't find 'go.d.conf' in [/usr/usr/local/etc/netdata /usr/usr/lib/netdata/conf.d], will use default configuration

workaround is to crate symbolic link to that path, but how can the path modified?

**Comment by ilyam8** [comment]
Hi

See

https://github.com/netdata/go.d.plugin/blob/e90c8f86724c1de1e10263512f288014aa744a44/cmd/godplugin/main.go#L86-L100

It searches for `<module_name>.conf` in the following (in that particular order) directories

https://github.com/netdata/go.d.plugin/blob/e90c8f86724c1de1e10263512f288014aa744a44/cmd/godplugin/main.go#L62-L63

---

If you run it in debug mode you can set path using `-c` parameter

see

> ./go.d.plugin --help

**Comment by ilyam8** [comment]
unbound module is enabled by default, having/not having `go.d.conf` doesnt matter, what matters is `unbound.conf`
