### ISSUE TITLE
go plugin k8s_kubelet token read from file issue

### ISSUE THREAD

**Issue by dids50x** [netdata/go.d.plugin#392]
Hello,

I am trying to add metrics from OpenShift into netdata agent's collect.
I installed netdata a few days ago, version 1.22.1.
OpenShift is based on Kubernetes, but 10255 port isn't available, so I use 10250 port instead.
I can locally do `curl -k -H "Authorization: Bearer <my-token>" https://127.0.0.1:10250/metrics`, and I get a ton of metrics.
I edited (with the utility `edit-config`) the config of the go plugin `k8s_kubelet` (k8s_kubelet.conf) like this:
```
jobs:
  - name: local
    url: https://127.0.0.1:10250/metrics
    tls_skip_verify: yes
    headers:
      X-API-Key: <my-token>
```

But when I test the check (logged-in as netdata user) I get an error, saying `/var/run/secrets/kubernetes.io/serviceaccount/token` file is missing:
```
-bash-4.2$ ./go.d.plugin -d -m k8s_kubelet
[ INFO  ] main[main] setup.go:91 maximum number of used CPUs 6
[ INFO  ] main[main] setup.go:94 minimum update every 1
[ INFO  ] main[main] create.go:72 loading 'k8s_kubelet' configuration
[ INFO  ] main[main] orchestrator.go:158 start main loop
[ WARN  ] k8s_kubelet[local] kubelet.go:69 error on reading service account token from '/var/run/secrets/kubernetes.io/serviceaccount/token': open /var/run/secrets/kubernetes.io/serviceaccount/token: no such file or directory
[ ERROR ] k8s_kubelet[local] kubelet.go:99 server returned HTTP status 403 Forbidden
[ ERROR ] k8s_kubelet[local] job.go:121 Check failed
[ WARN  ] main[main] start.go:41 k8s_kubelet[local]: autodetection failed
[ DEBUG ] main[main] orchestrator.go:173 tick 0
^C[ INFO  ] main[main] orchestrator.go:188 SIGINT received. Terminating...
-bash-4.2$
```

If I create the file and put my token in it, it says another error:
```
-bash-4.2$ ./go.d.plugin -d -m k8s_kubelet
[ INFO  ] main[main] setup.go:91 maximum number of used CPUs 4
[ INFO  ] main[main] setup.go:94 minimum update every 1
[ INFO  ] main[main] create.go:72 loading 'k8s_kubelet' configuration
[ INFO  ] main[main] orchestrator.go:158 start main loop
[ ERROR ] k8s_kubelet[local] kubelet.go:99 Get https://127.0.0.1:10250/metrics: net/http: invalid header field value "Bearer <my-token>\n" for key Authorization
[ ERROR ] k8s_kubelet[local] job.go:121 Check failed
[ WARN  ] main[main] start.go:41 k8s_kubelet[local]: autodetection failed
[ DEBUG ] main[main] orchestrator.go:173 tick 0
[ DEBUG ] main[main] orchestrator.go:173 tick 1
[ DEBUG ] main[main] orchestrator.go:173 tick 2
^C[ INFO  ] main[main] orchestrator.go:188 SIGINT received. Terminating...
-bash-4.2$
```

Some people seem to encounter the same kind of issue (`net/http: invalid header field value`):
[Trailing whitespace in tokenFile causes `net/http: invalid header field value` error](https://github.com/kubernetes/kubernetes/issues/52919)

But there is no trailing space in the file I created (I checked).

And the token shouldn't be read from the file if its already in the pugin's configuration file.

Could you help or solve this issue?

Thanks in advance.

Regards.

**Comment by ilyam8** [comment]
Hi

i see read token file error is not fatal

	b, err := ioutil.ReadFile(k.TokenPath)
	if err != nil {
		k.Warningf("error on reading service account token from '%s': %v", k.TokenPath, err)
	} else {
		k.Request.Headers["Authorization"] = "Bearer " + string(b)
	}

https://github.com/netdata/go.d.plugin/blob/d050efc3d1e5469ab4a7ba31e00dcd7608284afc/modules/k8s_kubelet/kubelet.go#L67-L72

---

```yaml
jobs:
  - name: local
    url: https://127.0.0.1:10250/metrics
    tls_skip_verify: yes
    headers:
      X-API-Key: <my-token>
```

i think it should be

```yaml
jobs:
  - name: local
    url: https://127.0.0.1:10250/metrics
    tls_skip_verify: yes
    headers:
      Authorization": "Bearer <my-token>"
```

**Comment by dids50x** [comment]
@ilyam8 Thank you, it works now.
