### ISSUE TITLE
Please provide details/sample on setting the per_user_details for OpenVPN

### ISSUE THREAD

**Issue by djpirra** [netdata/go.d.plugin#395]
I am currently trying to obtain information per user/client connected to my OpenVPN instance.
How can I set this up?
I can only seem to be able to have the global number of clients connected (not identified) and traffic.

**Comment by ilyam8** [comment]
Hi

I see it is not in the module readme but in the config

https://github.com/netdata/go.d.plugin/blob/47b6e368527ee761b5ac3f7e5960ba97702c4dd6/config/go.d/openvpn.conf#L81-L92


If you want to collect data for all user your jobs should be like

```yaml
jobs:
  - name: local
    address: 127.0.0.1:7505
    per_user_stats: 
      includes: 
        - *
```

**Comment by djpirra** [comment]
My configuration is and it does not work:

```YAML
jobs:
  - name: local
    address: 127.0.0.1:5555
    per_user_stats:
      includes:
        - *
```

If I leave only like this it works:

```YAML
jobs:
  - name: local
    address: 127.0.0.1:5555
    per_user_stats:
```

In any case, was I supposed to see each of the client ids connected?

**Comment by djpirra** [comment]
I had a look at the function on the OpenVPN plugin and it seems it is not prepared to parse the log structure I am having:


This is an example of my status log:

```
OpenVPN CLIENT LIST
Updated,Sat Jun 20 22:04:02 2020
Common Name,Real Address,Bytes Received,Bytes Sent,Connected Since
lsimoes_phone,2.51.53.193:52838,3219,4493,Sat Jun 20 22:03:50 2020
ROUTING TABLE
Virtual Address,Common Name,Real Address,Last Ref
10.8.0.5,lsimoes_phone,2.51.53.193:52838,Sat Jun 20 22:03:51 2020
GLOBAL STATS
Max bcast/mcast queue length,0
END
```

Is it not supported?

**Comment by ilyam8** [comment]
@djpirra oh, should be

```yaml
jobs:
  - name: local
    address: 127.0.0.1:5555
    per_user_stats:
      includes:
        - '*'
```

> In any case, was I supposed to see each of the client ids connected?

See `Per user charts`

https://github.com/netdata/go.d.plugin/tree/master/modules/openvpn#charts

**Comment by ilyam8** [comment]
To get user stats it uses `status 3\n` command

https://github.com/netdata/go.d.plugin/blob/47b6e368527ee761b5ac3f7e5960ba97702c4dd6/modules/openvpn/client/client.go#L74-L80

https://github.com/netdata/go.d.plugin/blob/47b6e368527ee761b5ac3f7e5960ba97702c4dd6/modules/openvpn/client/commands.go#L27-L29

**Comment by djpirra** [comment]
What does that mean?

**Comment by ilyam8** [comment]
What exactly are you asking about?

**Comment by djpirra** [comment]
I have put here an example of my status log file content...
It seems that the content does not follow what is expected in the code for the plugin...

What do you mean with the status 3? My log level is 3 in the configuration.

**Comment by djpirra** [comment]
This is the version I have installed:

https://github.com/theonemule/simple-openvpn-server

**Comment by ilyam8** [comment]
There are commands to get data from the OpenVPN Management Interface, see

https://github.com/netdata/go.d.plugin/blob/master/modules/openvpn/client/commands.go


This module doesnt parse any logs, it does tcp requests.

**Comment by ilyam8** [comment]
> It seems that the content does not follow what is expected in the code for the plugin...

What part of the code are you referencing? I think we are talking about different things.

There is python version

https://github.com/netdata/netdata/tree/master/collectors/python.d.plugin/ovpn_status_log

It parses openvpn log files.

**Comment by djpirra** [comment]
The other is working... I am not using the python version.
Ok I understand the Go module uses TCP to get the status information, then something is failing... How can I debug it?

**Comment by ilyam8** [comment]
> Ok I understand the Go module uses TCP to get the status information, then something is failing... How can I debug it?


Have you changes `- *` to `- '*'` in the config?


> How can I debug it?

https://github.com/netdata/go.d.plugin/tree/master/modules/openvpn#troubleshooting

**Comment by djpirra** [comment]
Yes and now I can see only the number of clients and the traffic...
There are no identified clients like expected... In my case I should be able to see a entry for lsimoes_phone right?

**Comment by ilyam8** [comment]
There should be 2 charts for every user.

Could you share debug output?

**Comment by djpirra** [comment]
I am trying to use: 
./go.d.plugin -d -m openvpn

but it says:
bash: ./go.d.plugin: No such file or directory

**Comment by djpirra** [comment]
This is what I see in the dashboard:
![image](https://user-images.githubusercontent.com/15980662/85212749-d7fdec00-b366-11ea-91c5-e3a708d80000.png)

**Comment by ilyam8** [comment]
You need to `cd` to the `plugins.d` dir, if you have `nd` installed in `/opt` it is

> /opt/netdata/usr/libexec/netdata/plugins.d

**Comment by djpirra** [comment]
bash: cd: /opt/netdata/usr/libexec/netdata/plugins.d: No such file or directory

**Comment by ilyam8** [comment]
As you see there is no reply from `127.0.0.1:5555`. It is likely because

> Currently, the OpenVPN daemon can at most support a single management client any one time.

You need to stop netdata service first, then run the plugin in debug mode

**Comment by djpirra** [comment]
This is what I got now after stopping Netdata first and still I don't see any client information:

```
[ INFO  ] openvpn[local] openvpn.go:101 using address: 127.0.0.1:5555, connect timeout: 2s, read timeout: 2s, write timeout: 2s
[ INFO  ] openvpn[local] openvpn.go:121 connected to OpenVPN v2.3.10, Management v1
[ INFO  ] openvpn[local] job.go:152 check success
[ INFO  ] openvpn[local] job.go:172 started, data collection interval 10s
[ DEBUG ] run[manager] run.go:41 tick 0
CHART 'netdata.execution_time_of_openvpn_local' '' 'Execution Time for openvpn_local' 'ms' 'go.d' 'netdata.go_plugin_execution_time' '' '145000' '10' '' 'go.d' 'openvpn'
DIMENSION 'time' '' '' '1' '1' ''

CHART 'openvpn_local.active_clients' '' 'Total Number Of Active Clients' 'active clients' 'clients' 'openvpn.active_clients' '' '70000' '10' '' 'go.d' 'openvpn'
DIMENSION 'clients' '' '' '1' '1' ''

BEGIN openvpn_local.active_clients
SET clients = 1
END

CHART 'openvpn_local.total_traffic' '' 'Total Traffic' 'kilobits/s' 'traffic' 'openvpn.total_traffic' 'area' '70001' '10' '' 'go.d' 'openvpn'
DIMENSION 'bytes_in' 'in' 'incremental' '8' '1000' ''
DIMENSION 'bytes_out' 'out' 'incremental' '8' '-1000' ''

BEGIN openvpn_local.total_traffic
SET bytes_in = 14192002
SET bytes_out = 201405877
END

BEGIN netdata.execution_time_of_openvpn_local
SET time = 1
END
```

**Comment by ilyam8** [comment]
ok, lets try to see returned data (again, `nd` should be disabled)

> echo "status 3" | nc localhost 5555

**Comment by djpirra** [comment]
Now I can see them:

```
djpirra@openvpnVM:/usr/libexec/netdata/plugins.d$ echo "status 3" | nc localhost 5555
>INFO:OpenVPN Management Interface Version 1 -- type 'help' for more info
TITLE   OpenVPN 2.3.10 x86_64-pc-linux-gnu [SSL (OpenSSL)] [LZO] [EPOLL] [PKCS11] [MH] [IPv6] built on Jan  9 2019
TIME    Sun Jun 21 13:09:40 2020        1592744980
HEADER  CLIENT_LIST     Common Name     Real Address    Virtual Address Bytes Received  Bytes Sent      Connected Since Connected Since (time_t)      Username
CLIENT_LIST     diana_mobile1_20191018-12M      87.201.62.85:61187      10.8.0.31       8662456 106121918       Sun Jun 21 12:44:04 2020      1592743444      UNDEF
HEADER  ROUTING_TABLE   Virtual Address Common Name     Real Address    Last Ref        Last Ref (time_t)
ROUTING_TABLE   10.8.0.31       lsimoes_mobile      87.201.62.85:61187      Sun Jun 21 13:09:02 2020        1592744942
GLOBAL_STATS    Max bcast/mcast queue length    1
END
```

**Comment by ilyam8** [comment]
ok, it seems i gave wrong example, syntax is

https://github.com/netdata/go.d.plugin/tree/master/pkg/matcher#syntax

>      <line>      ::= [ <not> ] <format> <space> <expr>


should be

```yaml
jobs:
  - name: local
    address: 127.0.0.1:5555
    per_user_stats:
      includes:
        - '* *'
```

**Comment by djpirra** [comment]
Now it appears as UNDEF even though in the status file of OpenVPN I can see the correct client name.

**Comment by ilyam8** [comment]
As you see `Unsername` is `UNDEF` in your case

|**HEADER CLIENT_LIST** |**Common Name** |**Real Address** |**Virtual Address** |**Bytes Received** |**Bytes Sent** |**Connected Since** |**Connected Since (time_t)** |**Username** |
|:---------------------:|:---------------------:|:---------------------:|:---------------------:|:---------------------:|:---------------------:|:---------------------:|:---------------------:|:---------------------:|
|CLIENT_LIST|lsimoes_mobile|87.201.62.85:61187|10.8.0.31|8662456|106121918|Sun Jun 21 12:44:04 2020|1592743444|UNDEF|

**Comment by ilyam8** [comment]
See my testdata (i took it from my old openvpn server)

https://github.com/netdata/go.d.plugin/blob/47b6e368527ee761b5ac3f7e5960ba97702c4dd6/modules/openvpn/client/testdata/status3.txt#L72-L73

Username is `pepe`.

**Comment by ilyam8** [comment]
I dont really remember details about using common name vs name, perhaps we need to use `common name` if `name` is `UNDEF`, i need to read documentation 🤷‍♂️

**Comment by ilyam8** [comment]
Ok, i didnt find an answer, it seem OpenVPN cant determine username, i dont have enough knowledge to understand it properly.

I assume using `Common Name` if `Username` is `UNDEF` is ok. @djpirra ?

**Comment by djpirra** [comment]
Yes I wanted to show the common name since in my case the authentication is just the certificate.

**Comment by ilyam8** [comment]
> Is it possible?

Yes, i will do a fix.

> Also, does Netdata allow to analyze aggregated data? Like for example the total traffic per day or per month?

No, atm it does not. You need to export data to some tsdb and do any aggregation/caclulation there.

**Comment by ilyam8** [comment]
@djpirra do you have `golang` installed? If so build the plugin from source, i added the fix.

```cmd
git clone https://github.com/netdata/go.d.plugin
cd go.d.plugin
make
stop netdata.service
cp bin/godplugin /usr/libexec/netdata/plugins.d/go.d.plugin
restart netdata.service
```

**Comment by djpirra** [comment]
I got this error:

```
djpirra@openvpnVM:~/go.d.plugin$ make
go mod download
go: unknown subcommand "mod"
Run 'go help' for usage.
Makefile:11: recipe for target 'download' failed
```

**Comment by djpirra** [comment]
Ok I have updated the Golang version to 1.14 and now during the make I get this:

Makefile:35: recipe for target 'vet' failed
make: *** [vet] Error 2

**Comment by ilyam8** [comment]
> go mod download
go: unknown subcommand "mod"

it seems it is not `1.14`

check it

> which go && go version

```
0 ilyam:go.d.plugin (master)$ which go && go version
/usr/local/bin/go
go version go1.14.4 darwin/amd64
```

**Comment by djpirra** [comment]
djpirra@openvpnVM:~/go.d.plugin$ go version
go version go1.14.4 linux/amd64


but if I do:
sudo go version
I still get the old version.

**Comment by ilyam8** [comment]
what about 

> ./hack/go-build.sh

**Comment by djpirra** [comment]
fixed the Go version under sudo but now it is spending loads of time...
CPU is 100% and IO is high... waiting for maybe 15 minutes.

**Comment by djpirra** [comment]
With the last command you gave I got this error:

djpirra@openvpnVM:~/go.d.plugin$ ./hack/go-build.sh
Building binaries for version: v0.19.2-2-gc4db41e
Building linux/amd64
# github.com/vmware/govmomi/vim25/types
fatal error: runtime: out of memory

**Comment by ilyam8** [comment]
[godplugin.tar.gz](https://github.com/netdata/go.d.plugin/files/4810113/godplugin.tar.gz)

**Comment by ilyam8** [comment]
it will be in the next release of `go.d.plugin`, i build linux/amd64 version^^

**Comment by djpirra** [comment]
Thanks @ilyam8 for the patience!
It is working now finally.

On one last note, do you know where I can get instructions on how I can analyze the aggregated data?
Wanted to understand the network consumption by each of the users. This would be really awesome if it would be given by Netdata.

Thanks again!

**Comment by ilyam8** [comment]
> On one last note, do you know where I can get instructions on how I can analyze the aggregated data?

Well, it is not possible using only Netdata atm, so you use Netdata as a collector, export data to some tsdb ([prometheus](https://learn.netdata.cloud/docs/agent/exporting/prometheus) is populat these days) and do calculations/aggregation there. As for instruction - depends on chosen tsdb, check its documention. Not much help from me, i am not a specialist.
