### ISSUE TITLE
hashstructure@v1.1.0: checksum mismatch

### ISSUE THREAD

**Issue by seife** [netdata/go.d.plugin#399]
the stanza

    go mod download
    go mod vendor

to create a vendor.tar.gz for packaging fails with a checksum mismatch:

    20-07-06 12:26:56 seife@vbox-seife:/dev/shm/go.d.plugin> go mod download
    go: verifying github.com/ilyam8/hashstructure@v1.1.0: checksum mismatch
            downloaded: h1:o3hpiGa1yergDO4AlUVBJGNvCEeaD+Ynu0OWYxee0iA=
            go.sum:     h1:N8t8hzzKLf2Da87XgC/DBYqXUmSbclgx+2cZxS5/klU=
    20-07-06 12:27:17 seife@vbox-seife:/dev/shm/go.d.plugin> go mod vendor
    go: downloading github.com/cloudflare/cfssl v1.4.1
    go: downloading github.com/prometheus/prometheus v2.5.0+incompatible
    go: downloading gopkg.in/yaml.v2 v2.3.0
    go: downloading golang.org/x/sys v0.0.0-20200116001909-b77594299b42
    go: downloading github.com/ilyam8/hashstructure v1.1.0
    go: downloading golang.org/x/net v0.0.0-20191027093000-83d349e8ac1a
    go: verifying github.com/ilyam8/hashstructure@v1.1.0: checksum mismatch
            downloaded: h1:o3hpiGa1yergDO4AlUVBJGNvCEeaD+Ynu0OWYxee0iA=
            go.sum:     h1:N8t8hzzKLf2Da87XgC/DBYqXUmSbclgx+2cZxS5/klU=

And no vendor/ directory is created.
Not sure if the checksum is wrong or if github.com/ilyam8/hashstructure@v1.1.0 has been tampered with.

**Comment by ilyam8** [comment]
whats is your golang version?

**Comment by seife** [comment]
Correct. I did initially download with golang-1.11.
Did retry with 1.14 but forgot to clean the cache m)

Now with clean cache everything is fine. Sorry for the noise ;-)
