### ISSUE TITLE
Improve README.md for matcher pkg

### ISSUE THREAD

**Issue by OdysLam** [netdata/go.d.plugin#419]
A user contacted support to setup the collector for openvpn. The issue was an incorrect understanding of the matcher syntax. The agent (me) also failed to understand how the pattern syntax works. The issue was resolved with the help from @ilyam8.

Thus, we need to improve the docs on the matcher in order to make it easier and simpler for people to use the patterns (which are already simpler than regex).  Some examples will help the user to understand the syntax and use this feature successfully.

## Resources
Forum Post: https://community.netdata.cloud/topic/65/how-to-use-properly-openvpn-conf-module-so-we-can-have-per_user_stats/2
Slack discussion: https://netdata-cloud.slack.com/archives/CSD2D3NTG/p1598438425053500

**Comment by ilyam8** [comment]
fixed in #422
