### ISSUE TITLE
split portcheck to tcpcheck and udpcheck

### ISSUE THREAD

**Issue by ilyam8** [netdata/go.d.plugin#42]
Currently `portcheck` is actually `tcpcheck`. The idea is to add udp check functionality (`telegraf` has it).

We have two ways:
 * add udp check to the existing `portcheck`
 * rename `portcheck` to `tcpcheck`, add new module `udpcheck`.

I want to make a separate module for udp checks becuaseit has different logic (that means different configuration parameters):

> NOTE: because the "udp" protocol does not respond to requests, it requires
> a send/expect string pair (see below).

@Ferroin @ktsaou @ccreamer @Wing924

**Comment by ktsaou** [comment]
How does UDP port check work?
I mean, there is no handshake on UDP, so you can't know if someone received it, until he replies. Or is it UDP check between telegraf nodes?

**Comment by l2isbad** [comment]
[net_response](https://github.com/influxdata/telegraf/tree/master/plugins/inputs/net_response)

>   The following options are required for UDP checks. For TCP, they are
>   optional. The plugin will send the given string to the server and then
>   expect to receive the given 'expect' string back.

i am not sure this is useful tho

**Comment by ktsaou** [comment]
ok, so you are supposed to provide 2 strings:

1. the packet to be sent
2. the packet to be received

ok, it can be done. But please keep in mind these packets may need to be binary (i.e. support some kind of hex encoding).

**Comment by l2isbad** [comment]
the question is shoud we add udp check to `portcheck` or implement it as a new module

I am personally for a separate module

**Comment by ktsaou** [comment]
whatever you prefer.
Keep in mind the request/response thing may be needed for both modules though.

**Comment by Ferroin** [comment]
I'd actually argue for a slightly different approach:

* Add the send/expect stuff to the existing portcheck module (if we do this with regex support for the expect side, we could possibly even get rid of the httpcheck module).
* Teach the module about connectionless protocols (that is, if the protocol is connectionless, require the send/expect stuff to work).
* Let users specify an arbitrary layer 4 protocol number.  Have special handling to recognize TCP and UDP as connection oriented and connectionless, and just require other protocol numbers to have it explicitly stated.

That gets us:
* Easy handling of new features.  They get implemented once, in one place.
* Trivial support for almost any layer 4 protocol.  This avoids the potentially slippery slope of having to add new protocols on demand.  Bonus points if it looks at `/etc/protocols` to get protocol number aliases.

**Comment by ktsaou** [comment]
@ilyam8 	if you can merge the two, @Ferroin 	proposal is best.
Actually the code should be quite close.
