### ISSUE TITLE
go.d.plugin constantly write on disk

### ISSUE THREAD

**Issue by llevet** [netdata/go.d.plugin#437]
Hi,

I use Netdata on SSD disk, and i configure it with "memory mode = save" to limit write on SSD.
But i see the process go.d.plugin regulary write on disk 25KB every 5 seconds.
It represent 500MB / Days.
What is written by this process?
It supposed only collect data and send it by pipe to netdata.
Thanks for your feedback.

**Comment by ilyam8** [comment]
Hi closed in favor of #438
