### ISSUE TITLE
go.d.plugin constantly write on disk

### ISSUE THREAD

**Issue by llevet** [netdata/go.d.plugin#438]
Hi,

I use Netdata on SSD disk, and i configure it with "memory mode = save" to limit write on SSD.
But i see the process go.d.plugin regulary write on disk 25KB every 5 seconds.
It represent 500MB / Days.
What is written by this process?
It supposed only collect data and send it by pipe to netdata.

Thanks for your feedback.

**Comment by llevet** [comment]
![image](https://user-images.githubusercontent.com/13711825/93387740-ff7f2a80-f869-11ea-908f-42f165077852.png)

**Comment by ilyam8** [comment]
Hi @llevet 

I am pretty sure it write jobs states

```cmd
[ilyam@ilyam-pc ~]$ ls /opt/netdata/var/lib/netdata/god-jobs-statuses.json
/opt/netdata/var/lib/netdata/god-jobs-statuses.json
```

It supposed to write **only on states changes and no more than every 5 seconds**.

https://github.com/netdata/go-orchestrator/blob/master/job/state/state.go


---

It seems there is a bug let me find it.

**Comment by ilyam8** [comment]
Ok, i checked and it works as expected

```cmd
[ilyam-pc netdata]# pwd
/opt/netdata/var/lib/netdata

[ilyam-pc netdata]# date
Ср 16 сен 2020 23:56:58 MSK

[ilyam-pc netdata]# ls -l | grep god
-rw-rw---- 1 netdata netdata 27424 сен 16 23:56 god-jobs-statuses.json

[ilyam-pc netdata]# rm god-jobs-statuses.json

[ilyam-pc netdata]# date
Чт 17 сен 2020 00:00:31 MSK
[ilyam-pc netdata]# ls -l | grep god
```

**Comment by ilyam8** [comment]
It can happens if there are some jobs in `retry` state.

I see we _save_ state on every retry task (so if `autodetection_retry' is 1 we save it every 1 second)

https://github.com/netdata/go-orchestrator/blob/25eff6ec645e1d90fdbebefda46dc8282dba6b1c/job/build/build.go#L251-L257

So [these methods](https://github.com/netdata/go-orchestrator/blob/25eff6ec645e1d90fdbebefda46dc8282dba6b1c/job/state/state.go#L52-L60) can be improved:

```go
func (m *Manager) Save(cfg confgroup.Config, state string) {
	m.state.add(cfg, state)
	m.triggerFlush()
}


func (m *Manager) Remove(cfg confgroup.Config) {
	m.state.remove(cfg)
	m.triggerFlush()
}
```

=>

```go
func (m *Manager) Save(cfg confgroup.Config, state string) {
	if changed := m.state.add(cfg, state); changed {
			m.triggerFlush()
    }
}


func (m *Manager) Remove(cfg confgroup.Config) {
	if changed := m.state.remove(cfg); changed {
		m.triggerFlush()
	}
}
```

**Comment by llevet** [comment]
Hi @ilyam8

You find the problem.
I remove the file /var/lib/netdata/god-jobs-statuses.json and it reappears after 5 seconds.
lots of jobs are marked as failed inside the files because this is a install from default config who enable all by default.

To workaround at this time , i mount /var/lib/netdata/ as  tmpfs

How to remove all this failed jobs or prevent generation of the "god-jobs-statuses.json" file?

Thanks.

**Comment by ilyam8** [comment]
> it reappears after 5 seconds.

Could you show the content?

- before delete
- after delete

i want to compare

**Comment by ilyam8** [comment]
> lots of jobs are marked as failed inside the files because this is a install from default config who enable all by default.


This is ok, they fail on start and there should be 1-2 writes in the beginning

> constantly write on disk

is not expected

**Comment by ilyam8** [comment]
what is your `go.d.plugin` version btw?

> ./go.d.plugin -v

**Comment by llevet** [comment]
[before_delete.txt](https://github.com/netdata/go.d.plugin/files/5235185/before_delete.txt)
[after_delete.txt](https://github.com/netdata/go.d.plugin/files/5235186/after_delete.txt)

go.d.plugin, version: v0.20.0

**Comment by llevet** [comment]
when i said 'constantly write on disk', in fact the file is recreate every 5 seconds.

**Comment by ilyam8** [comment]
> go.d.plugin, version: v0.20.0

Well, if that is the case then it should write every 10 seconds.

I changed its state save behavior in https://github.com/netdata/go-orchestrator/pull/49

---

- `v0.20.0-`: save every 10 seconds
- `v0.21.0+`: save only on states changes plus 5 seconds buffer (accumulate changes before writing)

**Comment by llevet** [comment]
Hi @ilyam8 

I'm just update netdata to v1.25.0-10-g05c9389
go.d.plugin, version: v0.22.0

It seem to be ok now, the file is not regenerate constantly.

Thanks !

**Comment by ilyam8** [comment]
Yeah, still it is very nice you drew my attention to it, i see how this saving states thing can be improved.
