### ISSUE TITLE
[mysql] missing userstats_cpu chart

### ISSUE THREAD

**Issue by kam1kaze** [netdata/go.d.plugin#442]
Hi,

I've just migrated from python mysql plugin to go and found that it does not contain `userstats_cpu` chart. I've checked the go code and have not found anything about it. Looks like it was missed.

Python chart is here:
https://github.com/netdata/netdata/blob/master/collectors/python.d.plugin/mysql/mysql.chart.py#L237

**Comment by ilyam8** [comment]
Indeed, i forgout about it because it was a separate chart - i added only per user charts

https://github.com/netdata/go.d.plugin/blob/b1e849a145abe8e620e49fb9b884ce70ef564d6e/modules/mysql/charts.go#L706-L738

**Comment by kam1kaze** [comment]
@ilyam8 thanks for the answer. Per user charts work fine.

**Comment by ilyam8** [comment]
Do you think we need to add it as aggregated chart (as in py) and make it a chart per user (like commands)?

**Comment by kam1kaze** [comment]
I would like to see it as aggregated chart (as in py), bcz I use it to determinate which services (client) are responsible for excessive load.
