### ISSUE TITLE
mysql plugins issues invalid "SHOW ALL SLAVE STATUS" for 5.5.68-MariaDB 

### ISSUE THREAD

**Issue by diegomontoya** [netdata/go.d.plugin#464]
Error log is showing that go/mysql plugin is issuing "SHOW ALL SLAVE STATUS" on a  5.5.68-MariaDB server which doesn't support this sql until version 10.2+. 

Nowhere in the documentation online or in the mysql.conf does it mention that "SHOW ALL SLAVE STATUS" is going to be executed. Online doc only means "SHOW SLAVE STATUS" for the go plugin. Due to this issue, replication stats are skipped. 

Version: v1.26.0-36-nightly

**Comment by ilyam8** [comment]
Hi, you are right, the collector uses `SHOW ALL SLAVE STATUS` for `mariadb` and `SHOW SLAVE STATUS` for `mysql`.

https://github.com/netdata/go.d.plugin/blob/a1c1fa72aba66e0f9dbf7ed9de239b849b47b474/modules/mysql/collect_slave_status.go#L21-L25 

And we don't check `mariadb` version at all

https://github.com/netdata/go.d.plugin/blob/a1c1fa72aba66e0f9dbf7ed9de239b849b47b474/modules/mysql/collect.go#L49-L51

**Comment by ilyam8** [comment]
>  which doesn't support this sql until version 10.2+.

Could you provide a link to the documentation? I couldn't find exact version.

**Comment by diegomontoya** [comment]
@ilyam8  Here you go

https://mariadb.com/docs/reference/es/sql-statements/SHOW_ALL_SLAVES_STATUS/

**Comment by ilyam8** [comment]
Thx! I will fix it.

**Comment by ilyam8** [comment]
@diegomontoya i think i've fixed the issue, still it would be nice if you test it - the fix is in the master, so you need to download the source code, compile it and replace `go.d.plugin`.
