### ISSUE TITLE
unbound module ignores cumulative setting

### ISSUE THREAD

**Issue by bjoe2k4** [netdata/go.d.plugin#477]
When unbound conf autodetection fails (`unbound.conf` contains only an include directive), the `cumulative: yes` keyword is ignored.

**Comment by ilyam8** [comment]
Hi @bjoe2k4 👋 

Could you show [the debug output](https://github.com/netdata/go.d.plugin/tree/master/modules/unbound#troubleshooting)?

**Comment by ilyam8** [comment]
And your `unbound.conf`

**Comment by ilyam8** [comment]
Ok, i see, it is `cumulative_stats`, not `cumulative`

https://github.com/netdata/go.d.plugin/blob/1cf8b1a2e13481327807a1bb208d024f0b94f3ee/modules/unbound/unbound.go#L50

**Comment by ilyam8** [comment]
Config file is wrong, i will fix it

https://github.com/netdata/go.d.plugin/blob/1cf8b1a2e13481327807a1bb208d024f0b94f3ee/config/go.d/unbound.conf#L77-L81

https://github.com/netdata/go.d.plugin/blob/1cf8b1a2e13481327807a1bb208d024f0b94f3ee/config/go.d/unbound.conf#L132

**Comment by ilyam8** [comment]
And readme is wrong 🙈

**Comment by ilyam8** [comment]
> When unbound conf autodetection fails (unbound.conf contains only an include directive)

About this. I think include directives should work, i remember [i tested them](https://github.com/netdata/go.d.plugin/tree/master/modules/unbound/config/testdata) 🤔

**Comment by bjoe2k4** [comment]
@ilyam8 thx for fixing. Your tests test for `include` but omit `include-toplevel`

This is my default debian unbound.conf
```
# Unbound configuration file for Debian.
#
# See the unbound.conf(5) man page.
#
# See /usr/share/doc/unbound/examples/unbound.conf for a commented
# reference config file.
#
# The following line includes additional configuration files from the
# /etc/unbound/unbound.conf.d directory.
include-toplevel: "/etc/unbound/unbound.conf.d/*.conf"
```
which results in 
```
[ INFO  ] unbound[local] init.go:19 reading '/etc/unbound/unbound.conf'
[ DEBUG ] unbound[local] init.go:27 empty configuration
```
