### ISSUE TITLE
unbound: config autodetection doesn't respect `include-toplevel` directive

### ISSUE THREAD

**Issue by ilyam8** [netdata/go.d.plugin#479]
@ilyam8 thx for fixing. Your tests test for `include` but omit `include-toplevel`

This is my default debian unbound.conf
```
# Unbound configuration file for Debian.
#
# See the unbound.conf(5) man page.
#
# See /usr/share/doc/unbound/examples/unbound.conf for a commented
# reference config file.
#
# The following line includes additional configuration files from the
# /etc/unbound/unbound.conf.d directory.
include-toplevel: "/etc/unbound/unbound.conf.d/*.conf"
```
which results in 
```
[ INFO  ] unbound[local] init.go:19 reading '/etc/unbound/unbound.conf'
[ DEBUG ] unbound[local] init.go:27 empty configuration
```

_Originally posted by @bjoe2k4 in https://github.com/netdata/go.d.plugin/issues/477#issuecomment-722613555_

**Comment by ilyam8** [comment]
[docs](https://nlnetlabs.nl/documentation/unbound/unbound.conf/):

>  For a more structural include option, the  `include-toplevel`:  directive
 can  be used.  This closes whatever clause is currently active (if any)
 and forces the use of clauses in the included  files  and  right  after
 this directive.

@bjoe2k4

Can you help me to understand `include-toplevel` and/or provide an examlpe?

**Comment by bjoe2k4** [comment]
Ugm, to me the difference between `include` and `include-toplevel` sounds mostly as syntactic sugar. While `include`d files preserve the context (=clause in the docs) like `server:`, `remote-control:`or `stub-zone:`,
`include-toplevel` forces an new context at the global (top) level. If there is no context in the file included by `include-toplevel`, then all directives are set on the global level.
