### ISSUE TITLE
[Triaging] Data collection modules migration state (`python`->`golang`)

### ISSUE THREAD

**Issue by ilyam8** [netdata/go.d.plugin#483]
# python.d (`python`)

We need to triage existing python modules - put them n `Do` or `Not Do` table.

---

<h2>

```diff
!~ Need Triage ~!
```

</h2>

- **UrlService**
    - [x] [apache](https://github.com/netdata/netdata/tree/master/collectors/python.d.plugin/apache)
    - [x] [couchdb](https://github.com/netdata/netdata/tree/master/collectors/python.d.plugin/couchdb)
    - [x] [dnsdist](https://github.com/netdata/netdata/tree/master/collectors/python.d.plugin/dnsdist)
    - [x] [elasticsearch](https://github.com/netdata/netdata/tree/master/collectors/python.d.plugin/elasticsearch)
    - [x] [energid](https://github.com/netdata/netdata/tree/master/collectors/python.d.plugin/energid)
    - [x] [go_expvar](https://github.com/netdata/netdata/tree/master/collectors/python.d.plugin/go_expvar)
    - [x] [haproxy](https://github.com/netdata/netdata/tree/master/collectors/python.d.plugin/haproxy)
    - [x] [httpcheck](https://github.com/netdata/netdata/tree/master/collectors/python.d.plugin/httpcheck)
    - [x] [icecast](https://github.com/netdata/netdata/tree/master/collectors/python.d.plugin/icecast)
    - [x] [ipfs](https://github.com/netdata/netdata/tree/master/collectors/python.d.plugin/ipfs)
    - [x] [monit](https://github.com/netdata/netdata/tree/master/collectors/python.d.plugin/monit)
    - [x] [nginx](https://github.com/netdata/netdata/tree/master/collectors/python.d.plugin/nginx)
    - [x] [nginx_plus](https://github.com/netdata/netdata/tree/master/collectors/python.d.plugin/nginx_plus)
    - [x] [phpfpm](https://github.com/netdata/netdata/tree/master/collectors/python.d.plugin/phpfpm)
    - [x] [powerdns](https://github.com/netdata/netdata/tree/master/collectors/python.d.plugin/powerdns)
    - [x] [puppet](https://github.com/netdata/netdata/tree/master/collectors/python.d.plugin/puppet)
    - [x] [rabbitmq](https://github.com/netdata/netdata/tree/master/collectors/python.d.plugin/rabbitmq)
    - [x] [retroshare](https://github.com/netdata/netdata/tree/master/collectors/python.d.plugin/retroshare)
    - [x] [riakkv](https://github.com/netdata/netdata/tree/master/collectors/python.d.plugin/riakkv)
    - [x] [springboot](https://github.com/netdata/netdata/tree/master/collectors/python.d.plugin/springboot)
    - [x] [tomcat](https://github.com/netdata/netdata/tree/master/collectors/python.d.plugin/tomcat)
    - [x] [traefik](https://github.com/netdata/netdata/tree/master/collectors/python.d.plugin/traefik)

- **ExecutableService**
    - [x] [adaptec_raid](https://github.com/netdata/netdata/tree/master/collectors/python.d.plugin/adaptec_raid)
    - [x] [chrony](https://github.com/netdata/netdata/tree/master/collectors/python.d.plugin/chrony)
    - [x] [exim](https://github.com/netdata/netdata/tree/master/collectors/python.d.plugin/exim)
    - [x] [hpssa](https://github.com/netdata/netdata/tree/master/collectors/python.d.plugin/hpssa)
    - [x] [logind](https://github.com/netdata/netdata/tree/master/collectors/python.d.plugin/logind)
    - [x] [megacli](https://github.com/netdata/netdata/tree/master/collectors/python.d.plugin/megacli)
    - [x] [nsd](https://github.com/netdata/netdata/tree/master/collectors/python.d.plugin/nsd)
    - [x] [postfix](https://github.com/netdata/netdata/tree/master/collectors/python.d.plugin/postfix)
    - [x] [samba](https://github.com/netdata/netdata/tree/master/collectors/python.d.plugin/samba)
    - [x] [varnish](https://github.com/netdata/netdata/tree/master/collectors/python.d.plugin/varnish)

- **LogService**
    - [x] [fail2ban](https://github.com/netdata/netdata/tree/master/collectors/python.d.plugin/fail2ban)
    - [x] [web_log](https://github.com/netdata/netdata/tree/master/collectors/python.d.plugin/web_log)

- **MySQLService**
    - [x] [mysql](https://github.com/netdata/netdata/tree/master/collectors/python.d.plugin/mysql)
    - [x] [proxysql](https://github.com/netdata/netdata/tree/master/collectors/python.d.plugin/proxysql)

- **SocketService**
    - [x] [dovecot](https://github.com/netdata/netdata/tree/master/collectors/python.d.plugin/dovecot)
    - [x] [gearman](https://github.com/netdata/netdata/tree/master/collectors/python.d.plugin/gearman)
    - [x] [hddtemp](https://github.com/netdata/netdata/tree/master/collectors/python.d.plugin/hddtemp)
    - [x] [memcached](https://github.com/netdata/netdata/tree/master/collectors/python.d.plugin/memcached)
    - [x] [ntpd](https://github.com/netdata/netdata/tree/master/collectors/python.d.plugin/ntpd)
    - [x] [redis](https://github.com/netdata/netdata/tree/master/collectors/python.d.plugin/redis)
    - [x] [squid](https://github.com/netdata/netdata/tree/master/collectors/python.d.plugin/squid)
    - [x] [uwsgi](https://github.com/netdata/netdata/tree/master/collectors/python.d.plugin/uwsgi)

- **SimpleService**
    - [x] [am2320](https://github.com/netdata/netdata/tree/master/collectors/python.d.plugin/am2320)
    - [x] [beanstalk](https://github.com/netdata/netdata/tree/master/collectors/python.d.plugin/beanstalk)
    - [x] [bind_rndc](https://github.com/netdata/netdata/tree/master/collectors/python.d.plugin/bind_rndc)
    - [x] [boinc](https://github.com/netdata/netdata/tree/master/collectors/python.d.plugin/boinc)
    - [x] [ceph](https://github.com/netdata/netdata/tree/master/collectors/python.d.plugin/ceph)
    - [x] [dns_query_time](https://github.com/netdata/netdata/tree/master/collectors/python.d.plugin/dns_query_time)
    - [x] [dockerd](https://github.com/netdata/netdata/tree/master/collectors/python.d.plugin/dockerd)
    - [x] [example](https://github.com/netdata/netdata/tree/master/collectors/python.d.plugin/example)
    - [x] [freeradius](https://github.com/netdata/netdata/tree/master/collectors/python.d.plugin/freeradius)
    - [x] [isc_dhcpd](https://github.com/netdata/netdata/tree/master/collectors/python.d.plugin/isc_dhcpd)
    - [x] [litespeed](https://github.com/netdata/netdata/tree/master/collectors/python.d.plugin/litespeed)
    - [x] [mongodb](https://github.com/netdata/netdata/tree/master/collectors/python.d.plugin/mongodb)
    - [x] [nvidia_smi](https://github.com/netdata/netdata/tree/master/collectors/python.d.plugin/nvidia_smi)
    - [x] [openldap](https://github.com/netdata/netdata/tree/master/collectors/python.d.plugin/openldap)
    - [x] [oracledb](https://github.com/netdata/netdata/tree/master/collectors/python.d.plugin/oracledb)
    - [x] [ovpn_status_log](https://github.com/netdata/netdata/tree/master/collectors/python.d.plugin/ovpn_status_log)
    - [x] [portcheck](https://github.com/netdata/netdata/tree/master/collectors/python.d.plugin/portcheck)
    - [x] [postgres](https://github.com/netdata/netdata/tree/master/collectors/python.d.plugin/postgres)
    - [x] [rethinkdbs](https://github.com/netdata/netdata/tree/master/collectors/python.d.plugin/rethinkdbs)
    - [x] [sensors](https://github.com/netdata/netdata/tree/master/collectors/python.d.plugin/sensors)
    - [x] [smartd_log](https://github.com/netdata/netdata/tree/master/collectors/python.d.plugin/smartd_log)
    - [x] [spigotmc](https://github.com/netdata/netdata/tree/master/collectors/python.d.plugin/spigotmc)
    - [x] [tor](https://github.com/netdata/netdata/tree/master/collectors/python.d.plugin/tor)
    - [x] [w1sensor](https://github.com/netdata/netdata/tree/master/collectors/python.d.plugin/w1sensor)

**Comment by ilyam8** [comment]
# charts.d (`bash`)

-  [`ap`](https://github.com/netdata/netdata/tree/master/collectors/charts.d.plugin/ap)
    - [ ] Who
    - [ ] Migrated
    - [ ] Feature Parity
    - [ ] Deprecation Alarm
    - [ ] Removed
-  [`apcupsd`](https://github.com/netdata/netdata/tree/master/collectors/charts.d.plugin/apcupsd)
    - [ ] Who
    - [ ] Migrated
    - [ ] Feature Parity
    - [ ] Deprecation Alarm
    - [ ] Removed
-  [`libreswan`](https://github.com/netdata/netdata/tree/master/collectors/charts.d.plugin/libreswan)
    - [ ] Who
    - [ ] Migrated
    - [ ] Feature Parity
    - [ ] Deprecation Alarm
    - [ ] Removed
-  [`nut`](https://github.com/netdata/netdata/tree/master/collectors/charts.d.plugin/nut)
    - [ ] Who
    - [ ] Migrated
    - [ ] Feature Parity
    - [ ] Deprecation Alarm
    - [ ] Removed
-  [`opensips`](https://github.com/netdata/netdata/tree/master/collectors/charts.d.plugin/opensips)
    - [ ] Who
    - [ ] Migrated
    - [ ] Feature Parity
    - [ ] Deprecation Alarm
    - [ ] Removed
-  [`sensors`](https://github.com/netdata/netdata/tree/master/collectors/charts.d.plugin/sensors)
    - [ ] Who
    - [ ] Migrated
    - [ ] Feature Parity
    - [ ] Deprecation Alarm
    - [ ] Removed

**Comment by ilyam8** [comment]
# node.d (`nodejs`)

-  [`fronius`](https://github.com/netdata/netdata/tree/master/collectors/node.d.plugin/fronius)
    - [ ] Who
    - [ ] Migrated
    - [ ] Feature Parity
    - [ ] Deprecation Alarm
    - [ ] Removed
-  [`named`](https://github.com/netdata/netdata/tree/master/collectors/node.d.plugin/named)
    - [ ] Who
    - [ ] Migrated
    - [ ] Feature Parity
    - [ ] Deprecation Alarm
    - [ ] Removed
-  [`sma_webbox`](https://github.com/netdata/netdata/tree/master/collectors/node.d.plugin/sma_webbox)
    - [ ] Who
    - [ ] Migrated
    - [ ] Feature Parity
    - [ ] Deprecation Alarm
    - [ ] Removed
-  [`snmp`](https://github.com/netdata/netdata/tree/master/collectors/node.d.plugin/snmp)
    - [ ] Who
    - [ ] Migrated
    - [ ] Feature Parity
    - [ ] Deprecation Alarm
    - [ ] Removed
-  [`stiebeleltron`](https://github.com/netdata/netdata/tree/master/collectors/node.d.plugin/stiebeleltron)
    - [ ] Who
    - [ ] Migrated
    - [ ] Feature Parity
    - [ ] Deprecation Alarm
    - [ ] Removed

**Comment by ilyam8** [comment]
# UrlService

<h2>

```diff
+! Do !+
```

</h2>


| Name              | Migrated | Feature Parity | Alarms Parity  |  Who   |
| ----------------- | -------- | -------------- | -------------- | ------ |
|                   |          |                |                |        |
|                   |          |                |                |        |

---

<h2>

```diff
-! Not Do !-
```

</h2>


| Name              | Reason                    |
| ----------------- | ------------------------- |
|                   |                           |
|                   |                           |

---

**Comment by ilyam8** [comment]
# ExecutableService

<h2>

```diff
+! Do !+
```

</h2>


| Name              | Migrated | Feature Parity | Alarms Parity  |  Who   |
| ----------------- | -------- | -------------- | -------------- | ------ |
|                   |          |                |                |        |
|                   |          |                |                |        |

---

<h2>

```diff
-! Not Do !-
```

</h2>


| Name              | Reason                    |
| ----------------- | ------------------------- |
|                   |                           |
|                   |                           |

---

**Comment by ilyam8** [comment]
# LogService

<h2>

```diff
+! Do !+
```

</h2>


| Name              | Migrated | Feature Parity | Alarms Parity  |  Who   |
| ----------------- | -------- | -------------- | -------------- | ------ |
|                   |          |                |                |        |
|                   |          |                |                |        |

---

<h2>

```diff
-! Not Do !-
```

</h2>


| Name              | Reason                    |
| ----------------- | ------------------------- |
|                   |                           |
|                   |                           |

---

**Comment by ilyam8** [comment]
# MySQLService

<h2>

```diff
+! Do !+
```

</h2>


| Name              | Migrated | Feature Parity | Alarms Parity  |  Who   |
| ----------------- | -------- | -------------- | -------------- | ------ |
|                   |          |                |                |        |
|                   |          |                |                |        |

---

<h2>

```diff
-! Not Do !-
```

</h2>


| Name              | Reason                    |
| ----------------- | ------------------------- |
|                   |                           |
|                   |                           |

---

**Comment by ilyam8** [comment]
# SocketService

<h2>

```diff
+! Do !+
```

</h2>


| Name              | Migrated | Feature Parity | Alarms Parity  |  Who   |
| ----------------- | -------- | -------------- | -------------- | ------ |
|                   |          |                |                |        |
|                   |          |                |                |        |

---

<h2>

```diff
-! Not Do !-
```

</h2>


| Name              | Reason                    |
| ----------------- | ------------------------- |
|                   |                           |
|                   |                           |

---

**Comment by ilyam8** [comment]
# SimpleService

<h2>

```diff
+! Do !+
```

</h2>


| Name              | Migrated | Feature Parity | Alarms Parity  |  Who   |
| ----------------- | -------- | -------------- | -------------- | ------ |
|                   |          |                |                |        |
|                   |          |                |                |        |

---

<h2>

```diff
-! Not Do !-
```

</h2>


| Name              | Reason                    |
| ----------------- | ------------------------- |
|                   |                           |
|                   |                           |

---

**Comment by thiagoftsm** [comment]
PostgreSQL has different libraries that can be used to do the migration, including [Sql Database](https://golang.org/pkg/database/sql/), that could also used with MySQL, but if we decide to work with MySQL and PostgreSQL completely independent, we could use the following libraries:

- [PGx](https://github.com/jackc/pgx) - This looks like the most complete library, but it does not offer support for versions older than 9.5
- [go-pg](https://github.com/go-pg/pg) - This library also offers ORM(Object relational map). It does not give additional information about the minimum PostgreSQL version it supports, but considering that PGx made a benchmark with this library, we can assume that it accepts the same versions.
- [Lib pq](https://github.com/lib/pq) - This is the library with the shortest description, on the other hand, it is the project with more stars on Github.

I think with any of these projects we can do the migration, because the python plugin executes query and after this it sends the results, the biggest problem would be the minimum PostgreSQL version supported.

**Comment by thiagoftsm** [comment]
While I was doing triage, I observed that we have the following avialable packages with at least 100 stars:

### Simple Service
- (Beanstalk)[https://github.com/beanstalkd/go-beanstalk]
- (CEPH){https://pkg.go.dev/github.com/ceph/go-ceph}
- (dns time){https://pkg.go.dev/github.com/miekg/dns}
- (docker){https://pkg.go.dev/github.com/docker/docker}
- (mongodb){https://www.mongodb.com/blog/post/quick-start-golang--mongodb--how-to-create-documents}
- (openldap){https://pkg.go.dev/gopkg.in/ldap.v2}
- (oracle){https://blogs.oracle.com/developers/how-to-connect-a-go-program-to-oracle-database-using-goracle}
- (postgresql{https://github.com/lib/pq}
- (rethinkdb){https://github.com/rethinkdb/rethinkdb-go}
- (TOR){https://github.com/ipsn/go-libtor}
- (freeradius){https://github.com/layeh/radius}

### Socket
- (gearman){https://github.com/mikespook/gearman-go]
- (memcache){https://github.com/bradfitz/gomemcache}
- (ntp){https://github.com/beevik/ntp}
- (redis){https://github.com/go-redis/redis}

**Comment by ilyam8** [comment]
triaged data moved to https://docs.google.com/spreadsheets/d/1SjcvRS8JSNaQUf9wWN7beBNDHQKXU9IzOJlNdZ1GglQ/edit?usp=sharing
