### ISSUE TITLE
vSphere Plugin does not work with self signed certificates

### ISSUE THREAD

**Issue by NiFuAxians** [netdata/go.d.plugin#489]
Even using tls_skip_verify, the plugin does not work with a vcenter with self signed certificates. Debug throws "certificate signed by unknown authority".

**Comment by ilyam8** [comment]
Hi. I see we pass that option creating a client (`tls_skip_verify` is InsecureSkipVerify field).

https://github.com/netdata/go.d.plugin/blob/e8b658940c2f6a3c2dac50306ad04caf370c876b/modules/vsphere/client/client.go#L51

---

Could you show debug output and your config (remove sensitive info if needed)?

**Comment by NiFuAxians** [comment]
For some reason my installation (using the kickstart script) did not update the correct version of the /go.d directory (I had multiple backup folders). Doing a fresh install worked like a charm. Issue closed
