### ISSUE TITLE
systemdunits returns an error

### ISSUE THREAD

**Issue by mjtice** [netdata/go.d.plugin#499]
Hi.

I'm trying to configure the systemdunits check on my CentOS 7.2 (also have tried CentOS 7.6)

When I run the plugin via debug it throws an error:

```
-bash-4.2$ /usr/libexec/netdata/plugins.d/go.d.plugin -d -m systemdunits
[ INFO  ] main[main] agent.go:106 instance is started
[ INFO  ] main[main] setup.go:39 loading config file
[ INFO  ] main[main] setup.go:47 looking for 'go.d.conf' in [/etc/netdata /usr/lib/netdata/conf.d]
[ WARN  ] main[main] setup.go:51 couldn't find config, will use defaults
[ INFO  ] main[main] agent.go:110 using config: enabled 'true', default_run 'true', max_procs '0'
[ INFO  ] main[main] setup.go:66 loading modules
[ INFO  ] main[main] setup.go:85 enabled/registered modules: 1/49
[ INFO  ] main[main] setup.go:90 building discovery config
[ INFO  ] main[main] setup.go:116 looking for 'systemdunits.conf' in [/etc/netdata/go.d /usr/lib/netdata/conf.d/go.d]
[ INFO  ] main[main] setup.go:120 couldn't find 'systemdunits' module config, will use default config
[ INFO  ] main[main] setup.go:128 dummy/read/watch paths: 1/0/0
[ INFO  ] discovery[manager] manager.go:90 registered discoverers: [dummy discovery]
[ INFO  ] discovery[manager] manager.go:95 instance is started
[ INFO  ] run[manager] run.go:30 instance is started
[ INFO  ] build[manager] build.go:106 instance is started
[ INFO  ] discovery[dummy] discovery.go:50 instance is started
[ INFO  ] discovery[dummy] discovery.go:51 instance is stopped
[ DEBUG ] build[manager] build.go:153 received config group ('systemdunits'): 1 jobs (added: 1, removed: 0)
[ DEBUG ] build[manager] build.go:288 building systemdunits[systemdunits] job, config: map[__provider__:dummy __source__:systemdunits autodetection_retry:0 module:systemdunits name:systemdunits priority:70000 update_every:10]
[ DEBUG ] systemdunits[systemdunits] systemdunits.go:60 unit names patterns: [*.service]
[ DEBUG ] systemdunits[systemdunits] systemdunits.go:61 timeout: 2s
[ ERROR ] systemdunits[systemdunits] systemdunits.go:76 error on listing units: Rejected send message, 2 matched rules; type="method_call", sender=":1.7886" (uid=596 pid=119432 comm="/usr/libexec/netdata/plugins.d/go.d.plugin -d -m s") interface="org.freedesktop.systemd1.Manager" member="ListUnitsByPatterns" error name="(unset)" requested_reply="0" destination="org.freedesktop.systemd1" (uid=0 pid=1 comm="/usr/lib/systemd/systemd --switched-root --system ")
[ ERROR ] systemdunits[systemdunits] job.go:153 check failed
```

My `systemunits.conf` is
```
jobs:
  - name: service-units
    include:
      - '*.service'
```

I'm not sure how to approach this as the error isn't very intuitive to me.

**Comment by ilyam8** [comment]
Hi @mjtice 👋 

The error doesn't say much to me too 😄 

`systemdunits` collector uses http://github.com/coreos/go-systemd/v22/dbus

`ListUnitsByPatternsContext` returns the error

https://github.com/netdata/go.d.plugin/blob/160dc4ee3ffd0e5f37567dacdd38125f8394d099/modules/systemdunits/collect.go#L51-L60

---

I will try to reproduce it. So it is just `CentOS 7.6` and netdata installed directly on the host or it is a docker container?

**Comment by mjtice** [comment]
Hi @ilyam8, thanks for looking.  It's not a container - netdata was installed via rpm and the go.d plugin/config was pulled from https://github.com/netdata/go.d.plugin/releases (0.25.0)

**Comment by ilyam8** [comment]
Ok, we checked it (thx to @thiagoftsm and @vlvkobal) and it seems we need to drop using `ListUnitsByPatterns` and use `ListUnits` and do filtering on our side - old versions of systemd has not such function.

If i remember it correctly `ListUnitsByPatterns` is less cpu intensive, so the best solution is to choose a function depends on systemd version.

**Comment by ilyam8** [comment]
`ListUnitsByPatterns` was added in `v230`.

**Comment by thiagoftsm** [comment]
I tested now and the PR fixed the problem as you can see at this [link](https://github.com/netdata/go.d.plugin/pull/502#pullrequestreview-535440131).

**Comment by ilyam8** [comment]
@mjtice i think we release new version next week, but you can build it from source to test/check (see my [comment](https://github.com/netdata/go.d.plugin/pull/502#issue-524635634))
