### ISSUE TITLE
prometheus module: configure when value is displayed as rate or not

### ISSUE THREAD

**Issue by benasse** [netdata/go.d.plugin#531]
I'm trying the prometheus module with the asterisk prometheus exporter, the result is not optimal.

For most of the graphs, it displays rates, but no cumulative values even for the cumulative values.
I quickly looked at the code it seems that some values are hard-coded : 
* https://github.com/netdata/go.d.plugin/blob/master/modules/prometheus/charts.go#L155
* https://github.com/netdata/go.d.plugin/blob/master/modules/prometheus/charts.go#L52

Do you plan to make it configurable?

I have attached an example of collected metrics to help better understand my request: [metrics.txt](https://github.com/netdata/go.d.plugin/files/5690973/metrics.txt)

**Comment by ilyam8** [comment]
Hi @benasse 👋 

You are right, indeed, incremental/not incremental dimensions algorithm logic is hardcoded.

> For most of the graphs, it displays rates, but no cumulative values even for the cumulative values.

I see your example, what values are you referring to? Those with `_count` suffix?

> Do you plan to make it configurable?

If we need it (it looks lik we do), then yes.

**Comment by benasse** [comment]
Hi @ilyam8,

In my example I refer to the following values:
```
prometheus_asterisk_exporter_local.asterisk_bridges_count
prometheus_asterisk_exporter_local.asterisk_bridges_channels_count
prometheus_asterisk_exporter_local.asterisk_calls_count
prometheus_asterisk_exporter_local.asterisk_calls_sum
prometheus_asterisk_exporter_local.asterisk_channels_count
prometheus_asterisk_exporter_local.asterisk_core_last_reload_seconds
prometheus_asterisk_exporter_local.asterisk_core_uptime_seconds
prometheus_asterisk_exporter_local.asterisk_endpoints_count
```

Effectively, it's the values with the `_count` sufix but also those with the `_sum` and `_seconds` sufix .

**Comment by ilyam8** [comment]
Reason of hardcoded logic is lack of clear understanding what user configurable options we need, i decided to add just few to not deal with breaking changes. And add them if there is request/use case.

The idea was to have prometheus collector with 2 modes - private and synthetic (dont really like those terms, but netdata statsd plugin uses them), see https://github.com/netdata/netdata/issues/9470

But at some point it became clear that configuring all those templates for synthetic mode in text files (with promql queries) is hard/error prone and that mode was put on a pause 😄 

---

> Effectively, it's the values with the _count sufix but also those with the _sum and _seconds sufix .

So there are 2 things we could do

- improve [default (hardcoded) logic](https://github.com/netdata/go.d.plugin/blob/master/modules/prometheus/charts.go#L155), probably there is a mistake.

- add a configuration option to rewrite metric type

> asterisk_calls_count

is a good example, it is a `counter` type metric and it makes sense to _chart_ it as a rate (`incremental`), but on the other hand it is make sense to chart it as is (`absolute`).

There is one problem - `absolute` means put a value in the db as is, `incremental` means calculate delta (cur-prev) and put the result in the db (so it is rate). Netdata doesn't apply any `rate` function to calc rate on the fly.

So if you change algorithm from `absolute` to `incremental` and restart netdata service you get

(code is value += 1 on every data collection)

<img width="1136" alt="Screenshot 2020-12-15 at 21 55 08" src="https://user-images.githubusercontent.com/22274335/102259704-7fc43300-3f20-11eb-865b-ed0134f10c32.png">


---

Back to 

> add a configuration option to rewrite metric type

How this option should look in the config? Any suggestions? 😄

**Comment by benasse** [comment]
I have read about the previous exchanges concerning the Prometheus colector, and indeed it is rather complex.

From my point of view, I would add a configuration option for the user to force a metric as an absolute, and this could be done via one or more paterns.

An example could be :
```
force_absolute_patern:
    - asterisk_bridges_count
    - asterisk_bridges_channels_count
```

**Comment by ilyam8** [comment]
Sorry for the delay 😅 

Adding such configuration option is not a big deal. 

- name `force_absolute_algorithm`
- value is a list of exact metric names
- works only for counter type metrics
 
@benasse sounds ok?

**Comment by benasse** [comment]
Sounds good!
As a complement, I think it would be nice to be able to specify paterns in addition to the exact name of the metrics as a parameter.

I quickly looked, if I produce a patch, it is above my competence considering my level in golang 😞

It might be a good idea to document the logic that the connenctor uses:

The prometheus collector uses the following logic to determine whether an input is absolute or not:
* The type of metric is Counter, Histogram or Summary
* The name of the metric ends with `_total`, `_sum` or `_count`
* The detected unit of the metric is `seconds` or `time`

It is possible to force a counter type metric to be a absolute value with the following option : `force_absolute_algorithm`

**Comment by ilyam8** [comment]
@benasse could you test #531?

You need recent version of golang to build it

(assuming you are building it on a linux server)

- build

```cmd
git clone https://github.com/ilyam8/go.d.plugin --branch=prometheus_force_absolute_algorithm go.d_prom_force_absolute_algorithm

cd go.d_prom_force_absolute_algorithm/

hack/go-build.sh
```

```cmd
[ilyam@pc go.d_prom_force_absolute_algorithm]$ bin/godplugin -v
go.d.plugin, version: v0.27.0-1-gb751e00
```

- stop netdata.service and replace go.d.plugin

```cmd
sudo systemctl stop netdata.service
sudo cp bin/godplugin /opt/netdata/usr/libexec/netdata/plugins.d/go.d.plugin
```

- modify `go.d/prometheus.conf`

```yaml
jobs:
  - name: ...
    url: ...
    force_absolute_algorithm:
      - pattern1
      - pattern2
```

- restart netdata.service

```cmd
sudo systemctl restart netdata.service
```

**Comment by benasse** [comment]
@ilyam8 I have tested and confirm that it works well !

**Comment by benasse** [comment]
I have just realised that the units were not necessarily correct: 
It is still added "/s" :

![image](https://user-images.githubusercontent.com/5676729/106030932-ec5d5080-60ce-11eb-94ae-85b9e686cb91.png)

**Comment by ilyam8** [comment]
Hawk eye! Thanks! I will fix it.
