### ISSUE TITLE
`filecheck`: add support for patterns

### ISSUE THREAD

**Issue by ilyam8** [netdata/go.d.plugin#532]
[filecheck](https://github.com/netdata/go.d.plugin/tree/master/modules/filecheck#filecheck) collector doesn't support patterns and requires to set exact paths to files/directories.

There is [no doubt patterns support is needed](https://github.com/netdata/go.d.plugin/pull/525), however, it is not that simple as it may look.

This issue is created to discuss the feature implementation.

I think there are 2 categories of entities - _static_ (include pattern w/o meta characters) and _dynamic_ (include pattern w/ meta characters). The question is how we need to treat dynamic ones, for example:

- do a discovery (filepath.Glob) every `discovery_every`
- add new dim to the chart if it has appropriate type (`file` for files, `dir` for dirs).
- delete dim from the chart if it is not in last discovered items.

It means that _File Existence_/_Dir Existence_ almost never false for dynamic entities.
Is this correct? I think we dont want to keep them in charts forever.

@BT-dschleich will this do for your use case? if not please describe what you would like it to be.

**Comment by ilyam8** [comment]
@vlvkobal @thiagoftsm if you have some ideas please share, the question is: files/dirs discovered via patterns (a path with a meta character), how we deal with them.

**Comment by BT-dschleich** [comment]
@ilyam8 Good Morning

This pretty much nails our use case. Thank you very much for progressing this into an issue.

I underestimated the dynamic nature of the charts so far, but now they seem quite important to me. In our use case we monitor the sizes of dynamically created (and deleted )directories, so without this the charts would pile up in the long run.

Indeed the File Existence/Dir Existence seems quite useless in the dynamic case, except maybe it can still show if the wildcard just did not match anything, even though exposing the Meta characters in the then empty glob string in the chart. 
To make the glob string chart not this useless we could make it a third chart type after File & Dir, maybe Wildcard, showing a chart for the number of Files/Dirs matched by that wildcard.

**Comment by ilyam8** [comment]
> To make the glob string chart not this useless we could make it a third chart type after File & Dir, maybe Wildcard, showing a chart for the number of Files/Dirs matched by that wildcard.

Yes, i didnt think about it, if this is useful metrics we can make such chart.

**Comment by BT-dschleich** [comment]
> > To make the glob string chart not this useless we could make it a third chart type after File & Dir, maybe Wildcard, showing a chart for the number of Files/Dirs matched by that wildcard.
> 
> Yes, i didnt think about it, if this is useful metrics we can make such chart.

The more I think about it the less useful it seems, at least for our specific use case, or others there might be a use to have the no match case visible in an extra chart.
