### ISSUE TITLE
typo in vsphere go.d plugin page

### ISSUE THREAD

**Issue by trent-thorkildsen** [netdata/go.d.plugin#533]
vsphere is spelt wrong in the command suggested at the bottom of: https://learn.netdata.cloud/docs/agent/collectors/go.d.plugin/modules/vsphere/

./go.d.plugin -d -m vshpere 

should be:

 ./go.d.plugin -d -m vsphere

**Comment by thiagoftsm** [comment]
Thank you very much to call attention for this @trent-thorkildsen ! Would you like to create a PR to fix yourself and giving a contribution for the project? 

Best regards!

**Comment by trent-thorkildsen** [comment]
No problem! I submitted the PR.

**Comment by thiagoftsm** [comment]
> No problem! I submitted the PR.

Nice, I am glad with this. As soon your PR is ready, I will review it :handshake:

**Comment by ilyam8** [comment]
fixed in https://github.com/netdata/go.d.plugin/pull/534
