### ISSUE TITLE
dnsmasq_dhcp and static/dynamic ranges

### ISSUE THREAD

**Issue by jonwaland** [netdata/go.d.plugin#546]
I have been trying to get the dnsmasq_dhcp module to correctly monitor both my dynamic and static IP DHCP allocations.

Previously I had a single DHCP-RANGE in the dnsmasq.config, which the module picks up, but of course it doesn't realise there are a bunch of statically allocated addresses. So I changed/cleaned the dnsmasq.config as follows:
```
dhcp-range=dynamic,192.168.1.1,192.168.1.63,12h
dhcp-range=static,192.168.1.64,192.168.1.254,48h
```
to provide two ranges - dynamic and static as per the dnsmasq documentation

And now the module misses all the DHCP ranges.

Log file from debug:

```
[ DEBUG ] main[main] main.go:111 plugin: name=go.d, version=v0.27.0
[ DEBUG ] main[main] main.go:113 current user: name=netdata, uid=999
[ INFO  ] main[main] agent.go:106 instance is started
[ INFO  ] main[main] setup.go:39 loading config file
[ INFO  ] main[main] setup.go:47 looking for 'go.d.conf' in [/etc/netdata /usr/lib/netdata/conf.d]
[ INFO  ] main[main] setup.go:54 found '/etc/netdata/go.d.conf
[ INFO  ] main[main] setup.go:61 config successfully loaded
[ INFO  ] main[main] agent.go:110 using config: enabled 'true', default_run 'true', max_procs '0'
[ INFO  ] main[main] setup.go:66 loading modules
[ INFO  ] main[main] setup.go:85 enabled/registered modules: 1/58
[ INFO  ] main[main] setup.go:90 building discovery config
[ INFO  ] main[main] setup.go:116 looking for 'dnsmasq_dhcp.conf' in [/etc/netdata/go.d /usr/lib/netdata/conf.d/go.d]
[ INFO  ] main[main] setup.go:123 found '/etc/netdata/go.d/dnsmasq_dhcp.conf
[ INFO  ] main[main] setup.go:128 dummy/read/watch paths: 0/1/0
[ INFO  ] discovery[manager] manager.go:90 registered discoverers: [file discovery: [file reader]]
[ INFO  ] discovery[manager] manager.go:95 instance is started
[ INFO  ] run[manager] run.go:30 instance is started
[ INFO  ] build[manager] build.go:106 instance is started
[ INFO  ] discovery[file manager] discovery.go:71 instance is started
[ INFO  ] discovery[file reader] read.go:39 instance is started
[ INFO  ] discovery[file reader] read.go:40 instance is stopped
[ DEBUG ] build[manager] build.go:153 received config group ('/etc/netdata/go.d/dnsmasq_dhcp.conf'): 2 jobs (added: 2, removed: 0)
[ DEBUG ] build[manager] build.go:295 building dnsmasq_dhcp[dnsmasq_dhcp] job, config: map[__provider__:file reader __source__:/etc/netdata/go.d/dnsmasq_dhcp.conf autodetection_retry:0 conf_dir:/etc/dnsmasq.d conf_path:/etc/dnsmasq.conf leases_path:/var/lib/misc/dnsmasq.leases module:dnsmasq_dhcp name:dnsmasq_dhcp priority:70000 update_every:1]
[ INFO  ] dnsmasq_dhcp[dnsmasq_dhcp] dhcp.go:86 start config : leases_path: [/var/lib/misc/dnsmasq.leases], conf_path: [/etc/dnsmasq.conf], conf_dir: [/etc/dnsmasq.d]
[ DEBUG ] dnsmasq_dhcp[dnsmasq_dhcp] autodetection.go:32 looking in '/etc/dnsmasq.conf'
[ DEBUG ] dnsmasq_dhcp[dnsmasq_dhcp] autodetection.go:35 found dhcp-range 'dynamic,192.168.1.1,192.168.1.63,12h'
[ DEBUG ] dnsmasq_dhcp[dnsmasq_dhcp] autodetection.go:35 found dhcp-range 'static,192.168.1.64,192.168.1.254,48h'
[ DEBUG ] dnsmasq_dhcp[dnsmasq_dhcp] autodetection.go:32 looking in '/etc/dnsmasq.d/README'
[ DEBUG ] dnsmasq_dhcp[dnsmasq_dhcp] autodetection.go:32 looking in '/etc/dnsmasq.d/ubuntu-fan'
[ ERROR ] dnsmasq_dhcp[dnsmasq_dhcp] dhcp.go:89 haven't found any dhcp-ranges
[ ERROR ] dnsmasq_dhcp[dnsmasq_dhcp] job.go:148 init failed
[ DEBUG ] build[manager] build.go:295 building dnsmasq_dhcp[dnsmasq_dhcp] job, config: map[__provider__:file reader __source__:/etc/netdata/go.d/dnsmasq_dhcp.conf autodetection_retry:0 conf_dir:/etc/dnsmasq.d conf_path:/etc/dnsmasq.conf leases_path:/etc/pihole/dhcp.leases module:dnsmasq_dhcp name:dnsmasq_dhcp priority:70000 update_every:1]
[ ERROR ] dnsmasq_dhcp[dnsmasq_dhcp] dhcp.go:72 open /etc/pihole/dhcp.leases: no such file or directory
[ ERROR ] dnsmasq_dhcp[dnsmasq_dhcp] job.go:148 init failed
[ DEBUG ] run[manager] run.go:41 tick 0
[ DEBUG ] run[manager] run.go:41 tick 1
[ DEBUG ] run[manager] run.go:41 tick 2
[ DEBUG ] run[manager] run.go:41 tick 3
[ DEBUG ] run[manager] run.go:41 tick 4
[ DEBUG ] run[manager] run.go:41 tick 5
[ DEBUG ] run[manager] run.go:41 tick 6
[ DEBUG ] run[manager] run.go:41 tick 7
[ DEBUG ] run[manager] run.go:41 tick 8
[ DEBUG ] run[manager] run.go:41 tick 9
^C[ INFO  ] main[main] agent.go:191 received interrupt signal (2). Terminating...
```

**Comment by ilyam8** [comment]
Hi @jonwaland 

Yes, it is a bug.

---

> Previously I had a single DHCP-RANGE in the dnsmasq.config, which the module picks up, but of course it doesn't realise there are a bunch of statically allocated addresses. 

Could you provide an example of the dnsmasq.config? If it doesn't work then let's fix this case too.

---

> So I changed/cleaned the dnsmasq.config as follows:
dhcp-range=dynamic,192.168.1.1,192.168.1.63,12h
dhcp-range=static,192.168.1.64,192.168.1.254,48h

Yes, dhcp range parsing fails. Seems like i didn't take into account this case with dynamic/static words.

https://github.com/netdata/go.d.plugin/blob/ff67eb1188e847099f4468ce637637f4c80c3ea7/modules/dnsmasq_dhcp/autodetection.go#L92-L107

**Comment by jonwaland** [comment]
original config:

```
dhcp-range=192.168.1.1,192.168.1.63,12h
dhcp-host=2c:cc:44:c3:3d:95,PS4,192.168.1.173,12h
```
etc

all the dhcp-hosts were at 192.168.1.64 and above.

**Comment by ilyam8** [comment]
## DHCP-Ranges

We need to find all `dhcp-range` or `dhcp-host` configuration directives.

This is implemented

- `dhcp-range`
https://github.com/netdata/go.d.plugin/blob/ff67eb1188e847099f4468ce637637f4c80c3ea7/modules/dnsmasq_dhcp/autodetection.go#L26-L34

- `dhcp-host`
https://github.com/netdata/go.d.plugin/blob/ff67eb1188e847099f4468ce637637f4c80c3ea7/modules/dnsmasq_dhcp/autodetection.go#L66-L73

> but of course it doesn't realise there are a bunch of statically allocated addresses

Do you say `dhcp-host` were not parsed? 

## Configuration files

Should be parsed recursively respecting `conf-dir` and `conf-file` options. Was added in https://github.com/netdata/go.d.plugin/pull/268

---

@jonwaland do you have only one `dnsmasq.config`?


I think i need to reread dnsmasq dhcp config file manual to fix the parsing

**Comment by jonwaland** [comment]
>Do you say dhcp-host were not parsed?

It appears so - with the config:
```
dhcp-range=192.168.1.1,192.168.1.63,12h
dhcp-host=2c:cc:44:c3:3d:95,PS4,192.168.1.173,12h
dhcp-host=blah,device,ip,12h
```
I get:
![image](https://user-images.githubusercontent.com/33437424/106211378-cb0a7a80-621c-11eb-98a4-cb1528d463c2.png)


with the config:
```
dhcp-range=dynamic,192.168.1.1,192.168.1.63,12h
dhcp-range=static,192.168.1.64,192.168.1.254,48h
dhcp-host=2c:cc:44:c3:3d:95,PS4,192.168.1.173,static
dhcp-host=blah,device,ip,static
```
I dont get a DNSMASQ DHCP graph set.

**Comment by ilyam8** [comment]
@jonwaland could you share your configuration file(s)?

I want to update `dnsmasq_dhcp` collector [testdata](https://github.com/netdata/go.d.plugin/tree/master/modules/dnsmasq_dhcp/testdata) and [tests](https://github.com/netdata/go.d.plugin/blob/master/modules/dnsmasq_dhcp/dhcp_test.go).

**Comment by jonwaland** [comment]
try these
[dnsmasq.conf.static.txt](https://github.com/netdata/go.d.plugin/files/5922767/dnsmasq.conf.static.txt)
[dnsmasq.leases.txt](https://github.com/netdata/go.d.plugin/files/5922768/dnsmasq.leases.txt)
[dnsmasq.conf.orig.txt](https://github.com/netdata/go.d.plugin/files/5922769/dnsmasq.conf.orig.txt)


(file names edited so I could attach. Contents edited to sanitise a little, and reduce the DHCP-HOSTs (I have 60+))

**Comment by ilyam8** [comment]
Ok, i think correct action is to spent some time on [dnsmasq documentation](http://www.thekelleys.org.uk/dnsmasq/docs/dnsmasq-man.html) and understand all the possible options to set

- `dhcp-range`

```
-F, --dhcp-range=[tag:<tag>[,tag:<tag>],][set:<tag>,]<start-addr>[,<end-addr>|<mode>][,<netmask>[,<broadcast>]][,<lease time>]
-F, --dhcp-range=[tag:<tag>[,tag:<tag>],][set:<tag>,]<start-IPv6addr>[,<end-IPv6addr>|constructor:<interface>][,<mode>][,<prefix-len>][,<lease time>]
```

 - `dhcp-host`
```
-G, --dhcp-host=[<hwaddr>][,id:<client_id>|*][,set:<tag>][tag:<tag>][,<ipaddr>][,<hostname>][,<lease_time>][,ignore]
```

and fix the parser properly. That is a littble bit confusing, for example i dont understand how is `dhcp-range=dynamic,192.168.1.1,192.168.1.63,12h` is a correct syntax, if, according docs, you need to use `tag:<tag>` and not just `<tag>` 😔 

Likely checking [dnsmasq source code](https://github.com/dnsmasq/dnsmasq) will be helpful.

**Comment by jonwaland** [comment]
I think static and dynamic are reserved "key words", and not tags or ids

**Comment by ilyam8** [comment]
ok, i see, it is `<mode>`

> The optional <mode> keyword may be static which tells dnsmasq to enable DHCP for the network specified, but not to dynamically allocate IP addresses: only hosts which have static addresses given via --dhcp-host or from /etc/ethers will be served.
> For IPv4, the <mode> may be proxy in which case dnsmasq will provide proxy-DHCP on the specified subnet. (See --pxe-prompt and --pxe-service for details.)




`-F, --dhcp-range=[tag:<tag>[,tag:<tag>],][set:<tag>,]<start-addr>[,<end-addr>|<mode>][,<netmask>[,<broadcast>]][,<lease time>]`

still, ther order is different^^ And i see no _dynamic_ `<mode>`

Source code: https://github.com/dnsmasq/dnsmasq/blob/ce5732e84fc46d7f99c152f736cfb4ef5ec98a01/src/option.c#L2701-L2711

There is only _static_ and _proxy_ modes.

**Comment by jonwaland** [comment]
interesting - I got my config by copying an example from the dnsmasq mailing list - so maybe I dont need the dynamic keyword.

re the order - the order isn't fixed from what I understand; sorry

**Comment by jonwaland** [comment]
from the man page:

> **--dhcp-range=::,constructor:eth0**
> 
> The optional **set:<tag>** sets an alphanumeric label which marks this network so that DHCP options may be specified on a per-network basis. When it is prefixed with 'tag:' instead, then its meaning changes from setting a tag to matching it. Only one tag may be set, but more than one tag may be matched.
> 
> The optional <mode> keyword may be **static** which tells dnsmasq to enable DHCP for the network specified, but not to dynamically allocate IP addresses: only hosts which have static addresses given via **--dhcp-host** or from /etc/ethers will be served. A static-only subnet with address all zeros may be used as a "catch-all" address to enable replies to all Information-request packets on a subnet which is provided with stateless DHCPv6, ie **--dhcp-range=::,static**
> 
> For IPv4, the <mode> may be **proxy** in which case dnsmasq will provide proxy-DHCP on the specified subnet. (See **--pxe-prompt** and **--pxe-service** for details.)
> 
> For IPv6, the mode may be some combination of **ra-only, slaac, ra-names, ra-stateless, ra-advrouter, off-link**.

I have changed my range config to:

```
dhcp-range=192.168.1.1,192.168.1.63,12h
dhcp-range=static, 192.168.1.64,192.168.1.254,48h
```

with no issues. There were no issues before either, but you are right - it wasn't correct!

**Comment by ilyam8** [comment]
@vlvkobal need your help here, let's check `dhcp-range`/`dhcp-host` parsing `c` code

**Comment by ilyam8** [comment]
New link https://thekelleys.org.uk/gitweb/?p=dnsmasq.git;a=blob;f=src/option.c;h=0a72406e9a38ab53456144802235cdc9491dfa28;hb=HEAD#l2990

**Comment by ilyam8** [comment]
> -F, --dhcp-range=[tag:<tag>[,tag:<tag>],][set:<tag>,]<start-addr>[,<end-addr>|<mode>][,<netmask>[,<broadcast>]][,<lease time>]

ipv4:
 - `[tag:<tag>[,tag:<tag>],][set:<tag>,]`
   - could be any number of tags (`tag:`, `net:` is an alias)
   - could be only one `set`. `set:` is optional prefix, any word before `<start-addr>` which is not `tag:<tag>` (or `net:<tag>`) considered as `set:`. (@jonwaland that is why `dhcp-range=dynamic,192.168.1.1,192.168.1.63,12h` works, `dynamic` is a `set:<tag>`).
   - tag, set order is not important (could be tag, set, tag or set, tag, tag or tag, tag, tag, set).
- `<start-addr>[,<end-addr>|<mode>]`
   - either end-addr or mode is required (`dhcp-range=1.1.1.1,12h` is invalid)
   - if `<start-addr>` > `<end-addr>` they are swapped (`dhcp-range=1.1.1.10,1.1.1.1,12h` => `dhcp-range=1.1.1.1,1.1.1.10,12h`)
