### ISSUE TITLE
dnsmasq - cache stats misleading

### ISSUE THREAD

**Issue by jonwaland** [netdata/go.d.plugin#547]
as per https://stackoverflow.com/questions/34036387/dnsmasq-statistics-not-match-cache-size-in-dnsmasq-conf

the stats for Cache entries (dnsmasq_local.cache_entries) are a little misleading.

MAX is the size of the cache (2048 in my case),
CURRENT is the total number of inserts since last flush - _not the number of current cache entries_ - mine is currently 10K....

I don't believe there is a stat for "current" usage of the cache.

**Comment by ilyam8** [comment]
@jonwaland hm 🤔 

I recall i couldn't find proper description of the dnsmasq cache stats...

The chart

https://github.com/netdata/go.d.plugin/blob/ff67eb1188e847099f4468ce637637f4c80c3ea7/modules/dnsmasq/charts.go#L18-L28

---

`cachesize` is `cachesize.bind.`

`cache_entries` is `;insertions.bind.` - `;evictions.bind.`

https://github.com/netdata/go.d.plugin/blob/ff67eb1188e847099f4468ce637637f4c80c3ea7/modules/dnsmasq/collect.go#L27-L32

Seem like the calculation is wrong. Do you understand why? Looks logical - number of entries == insertions - evictions.

**Comment by ilyam8** [comment]
Ok

- `insertions` is [`METRIC_DNS_CACHE_INSERTED`](https://github.com/imp/dnsmasq/blob/4e7694d7107d2299f4aaededf8917fceb5dfb924/src/cache.c#L1316-L1317)

> Variable cache_inserted increments on any successful commit of an entry to the cache, whether the inserting is new, or replacing something that expired. There is also such a thing as an unsuccessful or incomplete commit, which doesn't get counted by this variable.

- `evictions` is [`METRIC_DNS_CACHE_LIVE_FREED`](https://github.com/imp/dnsmasq/blob/4e7694d7107d2299f4aaededf8917fceb5dfb924/src/cache.c#L1320-L1321)

> Variable cache_live_freed has a rather complex meaning, but basically gets down to replacing an expired cache entry.

---

Seems like `insertions` - `evictions` wasn't a good idea and we need to remove `cache_entries` metric, you are right @jonwaland

**Comment by jonwaland** [comment]
Apologies for not replying - but yes - insertions-evictions isn't what you thought. Although it made sense syntactically and logically!
