### ISSUE TITLE
`supervisord` improvements

### ISSUE THREAD

**Issue by ilyam8** [netdata/go.d.plugin#554]
Requested in netdata/netdata#4852 by @ekexcello

- Summary (across all groups)

| Name        | Description |
| ----------- | ----------- |
| Uptime      | Total time when there is at least **one running process** in **any** group |
| Downtime    | Total time when there is **no running processes in all groups** |

- Per group

| Name        | Description |
| ----------- | ----------- |
| Uptime      | Total time when there is at least **one running process** |
| Downtime    | Total time when there is **no running processes**  |
| Average uptime    | Average uptime of **running** processes |
| Summarized uptime | Summarized uptime of all processes within the group | 
| Summarized downtime | summarizing time when no process was running in a group | 

@ekexcello did i understand you correctly?^^ Do you think `Summarized uptime` and `Summarized downtime` is a thing? Why do we need it?

**Comment by ekexcello** [comment]
Hello @ilyam8 
As for metrics, everything seems to be correct, just as you described.

As for summarized uptime and summarized downtime, they provide monitoring for scalability.
Supervisor common use case is site background (asynchronous) jobs, so these jobs can be considered down when no job is running, fully up when all the jobs are running, but in case something prevents jobs from being stable, total uptime will be lower then estimated, so jobs will be "running but experiencing some issues". 
I'd say these two options are probably not mandatory for everyone, can be provided as switchable options.

**Comment by ilyam8** [comment]
Ok, `Average uptime`, `Summarized uptime` and `Summarized downtime` is easy to add.

But those carried over time uptime/downtime a little bit tricky.

Copying your comment

> global uptime: single chart - summarized uptime of all groups (mean, summarized time when at least one process in each group was up since supervisord startup). If it will be complex to track across netdata restarts, this can be treated as 'since last supervisor or netdata restart'.

`since last supervisor or netdata restart` doesnt sound good

Would be nice to have exact uptime/downtime (we have start/stop/now for every process). Only if it impossible we need to consider to fallback to `since last netdata restart`. I don't like it because it doesn't make sense to me.

**Comment by ekexcello** [comment]
Hello @ilyam8 
Unfortunately, there seems to be no way to get this information from supervisor directly without modifying supervisor code. If there's a way to save last collected state and track status across netdata restarts?..

**Comment by ilyam8** [comment]
or instance, on start:
 - all stopped: `downtime = now - max([stopped1, ...])`
 - all running: `uptime = now - min([start1, ...])`

i mean probably we can calculate uptime/downtime using start/stop/now timestamps of the processes.

**Comment by ekexcello** [comment]
This seems to be acceptable solution, you are right. Anyway, this is better then saving some cache somewhere!

**Comment by ilyam8** [comment]
If you are still interested in this feature - consider [opening a feature request](https://github.com/netdata/netdata/issues/new?assignees=&labels=feature+request%2Cneeds+triage&template=FEAT_REQUEST.yml&title=%5BFeat%5D%3A+) in the netdata repo. Closing the issue because I plan to disable issues in this repo - will be using netdata/netdata.
