### ISSUE TITLE
Plugin missing

### ISSUE THREAD

**Issue by Mxater** [netdata/go.d.plugin#565]
I install netdata in 5 machines with centos 7, in all machines, go.d.plugin is missing.

``` 
# ps faxu | grep "[n]etdata"
netdata  10761  1.5  0.1 346940 32480 ?        Ssl  10:48   0:10 /usr/sbin/netdata -P /var/run/netdata/netdata.pid -D
netdata  10763  0.0  0.0  74592  2508 ?        Sl   10:48   0:00  \_ /usr/sbin/netdata --special-spawn-server
netdata  10857  0.1  0.0   9700  1540 ?        S    10:48   0:01  \_ /usr/bin/bash /usr/libexec/netdata/plugins.d/tc-qos-helper.sh 1
netdata  10876  1.9  0.1 165148 21688 ?        Sl   10:48   0:13  \_ /usr/bin/python /usr/libexec/netdata/plugins.d/python.d.plugin 1
netdata  10878  2.0  0.0  60564  4036 ?        S    10:48   0:14  \_ /usr/libexec/netdata/plugins.d/apps.plugin 1

```

![imagen](https://user-images.githubusercontent.com/4630666/112651769-7a358d80-8e2b-11eb-87f7-5b50ca4300da.png)

How I can install this module?

**Comment by ilyam8** [comment]
Hi @Mxater 

How did you install netdata? What's your netdata version?

> /usr/sbin/netdata -v

**Comment by Mxater** [comment]
I install netdata using `yum install netdata`.

This version `netdata v1.29.3`

**Comment by ilyam8** [comment]
Ok, what repo do you use? Do you use https://packagecloud.io/netdata/netdata?

**Comment by Mxater** [comment]
I use default repos

**Comment by ilyam8** [comment]
Then i suggest to switch to our repo on packagecloud

**Comment by Mxater** [comment]
I add the new repo, and reinstall with `yum resintall netdata` but the same, go.d still missing.

**Comment by Mxater** [comment]
I install packagecloud repo, but continue download from epel

![imagen](https://user-images.githubusercontent.com/4630666/112658605-532e8a00-8e32-11eb-9828-c8dedf2694ed.png)

**Comment by Mxater** [comment]
I fix it,
I use `yum --disablerepo="*" --enablerepo="netdata_netdata" install netdata` instead `yum --disablerepo="*" --enablerepo="netdata_netdata" install netdata`

**Comment by ilyam8** [comment]
@Mxater those are two identical commands

**Comment by Mxater** [comment]
I fix the commands

**Comment by ilyam8** [comment]
Ok, it is nice you managed to get it working 👍 Perhaps we need to add the command to our docs.

**Comment by ilyam8** [comment]
Oh, @Mxater i assume you get go.d.plgin when installing from our repo, am i right?

**Comment by Mxater** [comment]
Yep, now I have go.d.plugin running.

![imagen](https://user-images.githubusercontent.com/4630666/112675044-69921100-8e45-11eb-921f-5286c308c93f.png)
