### ISSUE TITLE
web_log: cannot unmarshal field_delimiter and value_delimiter

### ISSUE THREAD

**Issue by Habetdin** [netdata/go.d.plugin#571]
##### Bug report summary

`web_log` module with `log_type: ltsv` can't use character/string values of `field_delimiter` and `value_delimiter` parameters, while example suggest to use them. Module's example configuration produces the next warning:

```
[ WARN  ] build[manager] build.go:221 couldn't build web_log[test]: yaml: unmarshal errors:
  line 59: cannot unmarshal !!str `	` into uint8
  line 60: cannot unmarshal !!str `:` into uint8
```

##### OS / Environment

`20.04.2 LTS (Focal Fossa)`

##### Netdata version

```
Version: netdata v1.30.1
Configure options:  '--build=x86_64-linux-gnu' '--includedir=${prefix}/include' '--mandir=${prefix}/share/man' '--infodir=${prefix}/share/info' '--disable-silent-rules' '--libdir=${prefix}/lib/x86_64-linux-gnu' '--libexecdir=${prefix}/lib/x86_64-linux-gnu' '--disable-maintainer-mode' '--disable-dependency-tracking' '--prefix=/usr' '--sysconfdir=/etc' '--localstatedir=/var' '--libdir=/usr/lib' '--libexecdir=/usr/libexec' '--with-user=netdata' '--with-math' '--with-zlib' '--with-webdir=/var/lib/netdata/www' '--with-bundled-lws=externaldeps/libwebsockets' 'build_alias=x86_64-linux-gnu' 'CFLAGS=-g -O2 -fdebug-prefix-map=/usr/src/netdata=. -fstack-protector-strong -Wformat -Werror=format-security' 'LDFLAGS=-Wl,-Bsymbolic-functions -Wl,-z,relro' 'CPPFLAGS=-Wdate-time -D_FORTIFY_SOURCE=2' 'CXXFLAGS=-g -O2 -fdebug-prefix-map=/usr/src/netdata=. -fstack-protector-strong -Wformat -Werror=format-security'
Features:
    dbengine:                YES
    Native HTTPS:            YES
    Netdata Cloud:           YES
    Cloud Implementation:    Legacy
    TLS Host Verification:   YES
Libraries:
    jemalloc:                NO
    JSON-C:                  YES
    libcap:                  NO
    libcrypto:               YES
    libm:                    YES
    LWS:                     YES static v3.2.2
    mosquitto:               YES
    tcalloc:                 NO
    zlib:                    YES
Plugins:
    apps:                    YES
    cgroup Network Tracking: YES
    CUPS:                    YES
    EBPF:                    YES
    IPMI:                    YES
    NFACCT:                  YES
    perf:                    YES
    slabinfo:                YES
    Xen:                     NO
    Xen VBD Error Tracking:  NO
Exporters:
    AWS Kinesis:             NO
    GCP PubSub:              NO
    MongoDB:                 NO
    Prometheus Remote Write: YES
```

##### Installation method

`netdata/netdata` repository on `packagecloud`

##### Component Name

`go.d/web_log`

##### Steps To Reproduce

The next configuration, based on module README's example:

```yaml
jobs:
  - name: test
    path: /var/log/nginx/test-ltsv.log
    log_type: ltsv
    ltsv_config:
      field_delimiter: '	'
      value_delimiter: ':'
```

produces the next warning:

```
[ WARN  ] build[manager] build.go:221 couldn't build web_log[test]: yaml: unmarshal errors:
  line 59: cannot unmarshal !!str `	` into uint8
  line 60: cannot unmarshal !!str `:` into uint8
```

And then there're no parsing events after that.

Changing the values to fit the `uint8` type:

```yaml
    ltsv_config:
      field_delimiter: 9
      value_delimiter: 58
```

where the `9` is decimal code for the `'	' (tab)` and the `58` is the same for `':' (colon)` does fix the problem, but in a very non-intuitive way.

##### Expected behavior

Example-based configuration would work. Also, if your `field_delimiter` is `"\t"` and `value_delimiter` is `":"` (standard LTSV) they even can be omitted, which is not clear while reading the examples.

##### Actual behavior

LTSV parser doesn't work with sample config, but works with "hacked" `field_delimiter` and `value_delimiter` values.

**Comment by ilyam8** [comment]
Hi @Habetdin. 

You are right. Both `field_delimiter` and `value_delimiter` configuration options are not string type.

https://github.com/netdata/go.d.plugin/blob/a3358ddc27419cfb80960946ea5b763c223a6247/pkg/logs/ltsv.go#L13-L17

I see same goes for `csv`

https://github.com/netdata/go.d.plugin/blob/a3358ddc27419cfb80960946ea5b763c223a6247/pkg/logs/csv.go#L13-L15
