### ISSUE TITLE
Request to add charts to wmi plugin

### ISSUE THREAD

**Issue by zuckschwerdt** [netdata/go.d.plugin#586]
I'm using the WMI plugin and would like to chart and log additional metrics.

Specifically
- users: wmi key `windows_os_users`
- physical_memory: wmi keys `windows_cs_physical_memory_bytes`, `windows_os_physical_memory_free_bytes`
- paging: wmi keys `windows_os_paging_free_bytes`, `windows_os_paging_limit_bytes`

I don't need the full memory stats, just the basic values from the wmi_exporter "os" collector suffice.

Currently I'm using a python plugin to chart these (replacing the total size values with "total - free" for a stacked plot). Which sure isn't great, but works well enough.
The wmi plugin seems to already parse those values (https://github.com/netdata/go.d.plugin/blob/master/modules/wmi/collect_os.go#L10-L17), so I wanted to give my use-case for consideration.

**Comment by ilyam8** [comment]
Hi @zuckschwerdt 👋 

- physical_memory: do we need free/used chart? (used = os_physical_memory_bytes - os_physical_memory_free_bytes)
- paging: do we need free/used chart? (used = os_paging_limit_bytes - os_paging_free_bytes)

**Comment by zuckschwerdt** [comment]
Hi, thanks for the very quick feedback!

Sorry, my note was too short. I meant to say: I do use "total - free" for a stacked plot right now. It's not a requirement, I just like the stacked plot and am not  familar with the chart options to do it another way.

I would naturally prefer just the raw values (total, free) for logging and, if possible, charts that are easy to grasp -- whatever is best practice :)

**Comment by ilyam8** [comment]
Hey, @zuckschwerdt.

`wmi` collects `memory_available_bytes` and `visible_memory_bytes`.

On my windows vm:
 - `memory_available_bytes` == `os_physical_memory_free_bytes`.
 - `visible_memory_bytes` == `cs_physical_memory_bytes`.

The chart is _Memory Utilization_ (should be Usage btw 🙈):

https://github.com/netdata/go.d.plugin/blob/b731b131ddcb537db54b1204f64065ad55b3ca98/modules/wmi/charts.go#L160-L175

Not a Windows expert by any stretch. I guess we don't need `os_physical_memory_free_bytes` and `cs_physical_memory_bytes`, am i missing something?

**Comment by zuckschwerdt** [comment]
Thanks. Yes that would work if the "memory" collector is enabled -- which is the recommended way to run the wmi_exporter.
I my case I'm just running the wmi_exporter with defaults, the memory collector is not enabled then.
I don't have access to the Windows machines and deploying wmi_exporter with default settings is just the way it is for now -- totally my fault, i just wanted to give feedback on my use-case as it might be interesting and perhaps possible to allow.

**Comment by zuckschwerdt** [comment]
Oh I missed the point about CS vs OS. Yes I do see `windows_cs_physical_memory_bytes == windows_os_visible_memory_bytes` -- no need for CS then.

**Comment by ilyam8** [comment]
- [TotalPhysicalMemory](https://docs.microsoft.com/en-us/windows/win32/cimwin32prov/win32-operatingsystem)

> Total amount, in kilobytes, of physical memory available to the operating system. This value does not necessarily indicate the true amount of physical memory, but what is reported to the operating system as available to it.

- [TotalVisibleMemorySize](https://docs.microsoft.com/en-us/windows/win32/cimwin32prov/win32-operatingsystem)

> Total amount, in kilobytes, of physical memory available to the operating system. This value does not necessarily indicate the true amount of physical memory, but what is reported to the operating system as available to it.

**Comment by ilyam8** [comment]
@zuckschwerdt I plan to update [used packages versions](https://github.com/netdata/go.d.plugin/blob/master/go.mod) and some other fixes, right after that I will release a new version (i hope this week).

**Comment by zuckschwerdt** [comment]
Not sure if it's a problem or even relevant: I don't get the "_used_bytes" (`os_visible_memory_used_bytes`, `os_paging_used_bytes`) from wmi_exporter. I see only `os_visible_memory_bytes`, `os_physical_memory_free_bytes`, `os_paging_limit_bytes`, `os_paging_free_bytes`.

**Comment by ilyam8** [comment]
>  I don't get the "_used_bytes" 

We calculate it manually

https://github.com/netdata/go.d.plugin/blob/9263187b2f4766f8c69ea88c72e8d0e9f7d5942b/modules/wmi/collect.go#L48-L51
