### ISSUE TITLE
vcenter plugin unable to scrap data

### ISSUE THREAD

**Issue by zenjabba** [netdata/go.d.plugin#588]
I've confirmed that it can see the vcenter instance (it's able to detect everything inside the vcenter) but just unable to collect the performance data

vcenter version: 7

```cmd
[ INFO  ] vsphere[vcenter1] discover.go:140 discovering : found 1 dcs, 6 folders, 2 clusters (2 dummy), 2 hosts, 52 vms, process took 21.345794ms
[ INFO  ] vsphere[vcenter1] build.go:164 discovering : building : removed 1 vms (not powered on)
[ INFO  ] vsphere[vcenter1] build.go:23 discovering : building : built 1/1 dcs, 6/6 folders, 2/2 clusters, 2/2 hosts, 51/52 vms, process took 52.693µs
[ INFO  ] vsphere[vcenter1] hierarchy.go:18 discovering : hierarchy : set 2/2 clusters, 2/2 hosts, 51/51 vms, process took 6.59µs
[ INFO  ] vsphere[vcenter1] filter.go:29 discovering : filtering : filtered 2/2 hosts, 0/51 vms, process took 4.809µs
[ INFO  ] vsphere[vcenter1] metric_lists.go:30 discovering : metric lists : collected metric lists for 0/0 hosts, 51/51 vms, process took 16.485µs
[ INFO  ] vsphere[vcenter1] discover.go:74 discovering : discovered 0/2 hosts, 51/52 vms, the whole process took 21.533012ms
[ ERROR ] vsphere[vcenter1] vsphere.go:192 failed to scrape hosts metrics
```

**Comment by ilyam8** [comment]
@zenjabba thanks for reporting the issue. We discussed it with @Valamyrr in https://github.com/netdata/go.d.plugin/pull/583#issuecomment-865754864

**Comment by ilyam8** [comment]
The problem is all the discovered hosts got filtered

> filtered 2/2 hosts

No metrics collected => we treat it as an error


https://github.com/netdata/go.d.plugin/blob/f0c1fdbd6809b5dd60354089d7150fd82447fca2/modules/vsphere/collect.go#L37-L42

**Comment by zenjabba** [comment]
Bingo. Configuration was wrong.

**Comment by ilyam8** [comment]
Oh, I see, you didn't want to filter your hosts. Anyway, that is a bug and we will fix it.
