### ISSUE TITLE
support NETDATA_*_CONFIG_DIR env

### ISSUE THREAD

**Issue by Wing924** [netdata/go.d.plugin#59]
we need to support those env
```
NETDATA_STOCK_CONFIG_DIR=/usr/lib/netdata/conf.d
NETDATA_USER_CONFIG_DIR=/etc/netdata
NETDATA_CONFIG_DIR=/etc/netdata
```

config search priority:

1. NETDATA_CONFIG_DIR
1. NETDATA_USER_CONFIG_DIR
1. NETDATA_STOCK_CONFIG_DIR
1. {go.d.plugin}/../../../../etc/netdata

**Comment by ilyam8** [comment]
`NETDATA_CONFIG_DIR` 

> the previous variable NETDATA_CONFIG_DIR is still supported, but should be deprecated as it is now misleading

`NETDATA_USER_CONFIG_DIR` == `NETDATA_CONFIG_DIR`
