### ISSUE TITLE
PHP-FPM socket monitoring docs

### ISSUE THREAD

**Issue by ffraenz** [netdata/go.d.plugin#590]
The documentation of the PHP-FPM module briefly mentions how to connect directly to a PHP-FPM socket instead of routing the requests through a web server. This is perfect for my use case where each website in a shared hosting environment receives an own socket. While implementing this I stumbled upon some gotchas, though.

I am using netdata v1.31.0.

First, when configuring phpfpm jobs using sockets as mentioned in the documentation, they always fallback to `using HTTP client, URL: http://127.0.0.1/status?full&json`. I guess the default job URL gets injected and gets priority over the socket setting, as specified here:
https://github.com/netdata/go.d.plugin/blob/ec9980149c3d32e4a90912826edd344dfb0413ac/modules/phpfpm/init.go#L11-L19

Only when explicitly setting the `url` attribute of a job to the empty string the module uses the socket client as I expected earlier. I'd suggest to either add this to [the documentation](https://github.com/netdata/go.d.plugin/tree/master/modules/phpfpm) or change the logic the config is processed.

```yaml
jobs:
  - { "name": "local_socket_1", "socket": "/tmp/php-fpm-1.sock", "url": "" }
  - { "name": "local_socket_2", "socket": "/tmp/php-fpm-2.sock", "url": "" }
```

Secondly, the PHP-FPM status page needs to be enabled (as documented) and set to `/status` (not documented) for the given PHP-FPM pool conf:

```
pm.status_path = /status
```

I thought setting the `status_path` to `/status` would expose the status page through the web server and/or would block any other app/website endpoints at `/status` so I first went with a different path. I quickly found out that both problems can be resolved in the web server config. The fact that I didn't know that the `status_path` needs to be explicitly set to `/status` kept me debugging for a while, though, until I found this piece of code. Let's add it to the docs, too.
https://github.com/netdata/go.d.plugin/blob/ec9980149c3d32e4a90912826edd344dfb0413ac/modules/phpfpm/client.go#L111-L119

**Comment by ilyam8** [comment]
Hi, @ffraenz. Thanks for the issue!

> Only when explicitly setting the url attribute of a job to the empty string the module uses the socket client

You are right, I think we can consider that as a bug. If `socket` is set we need to use the option.


> I quickly found out that both problems can be resolved in the web server config.

Are you willing to make a PR? I agree that we need to update our docs.

**Comment by ilyam8** [comment]
@ffraenz ok, I went forward and changed both initialization logic and the docs

> https://github.com/netdata/go.d.plugin/pull/591/files

Check it, please.

**Comment by ffraenz** [comment]
@ilyam8 Thank you for your quick response and proposed changes. Sorry I wasn't able to get back to you sooner. I think the code changes fix the issue as there is no default `socket` afaik. The docs requirement "access to `status` page via web server." might be misleading as you bypass any web server when you use the PHP-FPM socket directly. In my case I want to use this Netdata module with a socket without exposing the status page to the world via the web server.

**Comment by ilyam8** [comment]
> The docs requirement "access to status page via web server." might be misleading as you bypass any web server when you use the PHP-FPM socket directly.

I agree. If you have time/willing you can make a PR with the changes/rewording or suggest them here. I will update the docs.

**Comment by ffraenz** [comment]
I'll open a pull request and suggest changes as soon as I get back to it. Thank you!

**Comment by ilyam8** [comment]
@glesys-andreas @ffraenz hi, guys. I know you used php-fpm collector via socket connection, can you help me with https://github.com/netdata/netdata/discussions/12312?
