### ISSUE TITLE
add MongoDB collector

### ISSUE THREAD

**Issue by ilyam8** [netdata/go.d.plugin#594]
We need to rewrite [python mongodb collector](https://github.com/netdata/netdata/tree/master/collectors/python.d.plugin/mongodb#mongodb-monitoring-with-netdata) in Golang.

There are several ways to do it:
 1. _mirror_ python module
 2. rewrite from scratch

### mirror python module

This means doing the same queries, collecting the same metrics, creating the same charts. The problem with it - python version is outdated.

### rewrite from scratch (preferred)

This means to do some research first:
 - read about [MongoDB monitoring](https://docs.mongodb.com/manual/administration/monitoring/) (single setup, replication, sharding, etc.).
 - check existing open-source MongoDB collectors:
   - [percona/mongodb_exporter](https://github.com/percona/mongodb_exporter)
   - [telegraf/mongodb](https://github.com/influxdata/telegraf/tree/master/plugins/inputs/mongodb#mongodb-input-plugin)
   - etc.
 - do a proposal (what queries we need, sample output, how to group metrics into charts, etc.)
 - implement according to the proposal (split the work into several PRs if needed (likely yes))

---

**Comment by georgeok** [comment]
Having played with mongo for a while now I propose to get 4 pillars of metrics and 4 PR accordingly:

1. serverStatus which return a general view of the database.
2. dbStats which reflect to the storage use and and data volumes. This one has a lot of parameters and appropriate grouping must be evaluated carefully to see where we get the most value without filling the dashboard with charts.
3. replSetGetStatus to the see the replica set status
4.  sharded cluster status


Initially until we have the basic of the plugin working with multiple database and authentication, I suggest to start with `serverStatus` and group the metrics into 2 charts, one with the storage parameters(disk, ram usage, etc.) in bytes and one with the storage counters (collections, indexes, view, etc.) as the first PR

**Comment by ilyam8** [comment]
Looks good @georgeok, I agree with both:
 - a PR per area (server stats, db stats, etc.).
 - start with server stats.

Not sure about 

> into 2 charts

I will check [the PR](https://github.com/netdata/go.d.plugin/pull/598)

**Comment by ilyam8** [comment]
Related https://github.com/netdata/netdata/issues/5897

**Comment by georgeok** [comment]
@ilyam8 
For the second part of this issue, `dbstats` I suggest that we collect the following metrics:

Aggregated for all databases
- absolute number of collections, views, indexes (1 chart)
-  absolute number of documents  (1 chart)
- data size, index size storage size in bytes (1 chart)

and also have a configuration flag that enables per database statistics. That would be:
- absolute number of collections, views, indexes (1 chart/**per database**)
-  absolute number of documents  (1 chart/**per database**)
- data size, index size storage size in bytes (1 chart/**per database**)
That would give disabled by default as some servers may have a large number of databases. For example it would be an overkill to have 3 charts for 50 databases = 150 charts. For use cases with small number of databases up to 5 maybe it makes sense to see where does the heavy lifting happens.

We could also introduce another configuration field with an array of database names that our users explicitly want to monitor and have separate charts for them and that would be 3 charts/database like above.

Please let me know what you think.

**Comment by ilyam8** [comment]
@georgeok thanks for sharing your ideas before implementing them 👍 

---

> For the second part of this issue, dbstats

I think collecting `dbstats` should be optional (`collect_dbstats: yes/no`). Not sure about the default 🤷 Not important now.

> 1 chart/per database => 3 charts for 50 databases = 150 charts

How about making a chart per metric? In that case, we get few charts with (potentially) a lot of dimensions. Which is better in my opinion. 

> Aggregated for all databases

Do we get aggregate stats or do we need to calculate them using per db stats?

**Comment by georgeok** [comment]
> How about making a chart per metric? In that case, we get few charts with (potentially) a lot of dimensions. Which is better in my opinion.

This makes more sense, yes...

> Do we get aggregate stats or do we need to calculate them using per db stats?

We have to run `dbstats` for each database and aggregate them using a simple sum algorithm. The database gives as separate stats per database unfortunately.

There is also a catch in the docs that drew my attention:
> The time required to run the command depends on the total size of the database. Because the command must touch all data files, the command may take several seconds to run.

https://docs.mongodb.com/manual/reference/command/dbStats/#behavior 
and having it as optional (`collect_dbstats: yes/no`) as you said might prove to be very important.

**Comment by ilyam8** [comment]
> The time required to run the command depends on the total size of the database. Because the command must touch all data files, the command may take several seconds to run

Then let's have it disabled by default.


> We have to run dbstats for each database and aggregate them using a simple sum algorithm.

What do we do with filtering? 
- query all the databases to have _correct_ summary stats
- filter out specific databases for per db stats

?

I think we can do the following:
 - no need for summary charts
 - make dbstats charts `stacked` type (so summary is visually visible)

---

> We have to run dbstats for each database

Ok, it means that we need to add database discovery and do it periodically.

**Comment by georgeok** [comment]
> What do we do with filtering?
> 
> query all the databases to have correct summary stats
> filter out specific databases for per db stats

Almost yes, I was thinking including in the sum only the "enabled" databases to avoid querying the all, but since there is no need for summary charts we won't have that problem

**Comment by georgeok** [comment]
Following on, for the replica set chart I suggest that we use 3 charts. These will be:

1.  Replication set member heartbeat latency: `db server time - lastheartbeat`. Diff between the server time and the last heartbeat command for non-primary members. This will be a stack chart.
2.  Replication lag: `db server time - optimeDate`  for all members. This will be a stack chart
3. Ping: milliseconds that a round-trip packet takes to travel between the remote member and the local instance for non-primary member. This will be a line chart.

Dimension IDs should include the name of the replica set member. For example, `ping_cluster0-shard-00.mongodb.net:2701`

**Comment by ilyam8** [comment]
@georgeok i see [python mongodb](https://github.com/netdata/netdata/blob/master/collectors/python.d.plugin/mongodb/mongodb.chart.py) executes two commands:
 - [replSetGetStatus](https://docs.mongodb.com/manual/reference/command/replSetGetStatus/)
 - [getReplicationInfo](https://docs.mongodb.com/manual/reference/method/db.getReplicationInfo/)

Where do those 1-3 come from?

**Comment by ilyam8** [comment]
Ok, answering my own question - "replSetGetStatus". I agree with the suggested charts.
