### ISSUE TITLE
mongodb chart typo - "mongob" instead of "mongodb"

### ISSUE THREAD

**Issue by bompus** [netdata/go.d.plugin#635]
https://github.com/netdata/go.d.plugin/blob/b06235c0b799755f21487010664bf4c7519a6984/modules/mongodb/charts.go#L92

I believe this should be `mongodb.connections_rate` instead of `mongb.connections_rate` as it shows up under mongb -> connections in the dashboard overview.

**Comment by ilyam8** [comment]
Hi, @bompus. You are right, thanks for reporting the issue.

> shows up under mongb -> connections in the dashboard overview.

Could you post a screenshot?

**Comment by bompus** [comment]
![mongb](https://user-images.githubusercontent.com/253635/144290987-ad877fa8-c8ba-4d07-ab8e-16952dbee692.png)

**Comment by ilyam8** [comment]
Thanks!
