### ISSUE TITLE
Is the license GPL-3.0-or-later or GPL-3.0-only

### ISSUE THREAD

**Issue by HRio** [netdata/go.d.plugin#640]
Not clear what the license of this work is, it only ships a gnu standard `LICENSE` file, but non of the other files mentions if it is
* GPL-3.0-or-later
or
* GPL-3.0-only

can this be clarified?

**Comment by ilyam8** [comment]
Closing this issue because I plan to disable issues for this repo - we will use netdata/netdata. But I have this question in mind and we will clarify about the license.
