### ISSUE TITLE
Haproxy parsing error

### ISSUE THREAD

**Issue by darkobas2** [netdata/go.d.plugin#642]
Hi

First thank you for this product. Its really amazing

I get errors trying to parse haproxy csv via http
````
go.d ERROR: haproxy[haproxy-2] strconv.ParseFloat: parsing ",FRONTEND,,,11,12,50000,23,3993,107966,0,0,0,,,,,OPEN,,,,,,,,,1,2,0,,,,0,1,0,1,,,,0,11,0,11,0,0,,1,1,23,,,0,0,0,0,,,,,,,,,,,,,,,,,,,,,http,,1,1,23,23,0,0,0,,,0,0,,,,,,,0,,,,,,,-,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,": invalid syntax
````

regards

**Comment by ilyam8** [comment]
The haproxy module [requirement](https://github.com/netdata/go.d.plugin/tree/master/modules/haproxy#requirements) is HAProxy v2.0+ (or 1.9r1+ for Enterprise users) with enabled PROMEX addon. I think you are using v1+ - try to use https://github.com/netdata/netdata/tree/master/collectors/python.d.plugin/haproxy#haproxy-monitoring-with-netdata.
