### ISSUE TITLE
mongodb replica set member going offline causes go.d.plugin to crash / disconnect

### ISSUE THREAD

**Issue by bompus** [netdata/go.d.plugin#645]
You can reproduce this bug when connected to a MongoDB replica set by shutting down any PRIMARY or SECONDARY member of the replica set. For me, shutting down the current PRIMARY is easiest to reproduce the issue.

I'm not sure if the issue is when it tries to collect stats when there is no PRIMARY voted in, or if it is simply the fact that the previously-connected replica set member is no longer connectable.

I'm also not sure if this would happen when a non-replica-set MongoDB instance goes offline, or if it is isolated to replica set logic.

I came across this issue twice now during upgrading MongoDB server versions on all 3 replica set members, which naturally has the previously marked PRIMARY server become unavailable / non-responsive during the upgrade process.

To fix, I need to `systemctl restart netdata` on all 3 servers that are part of the MongoDB replica set.

```
2022-02-02 16:31:49: netdata ERROR : PLUGINSD[go.d] : requested a SET to dimension with id 'heartbeat_latency_local-1.wg0:27017' on stats 'mongodb_local.replication_heartbeat_latency' (mongodb_local.replication_heartbeat_latency) on host 'local-1', which does not exist. Disabling it.
2022-02-02 16:31:49: netdata INFO  : PLUGINSD[go.d] : PARSER ended
2022-02-02 16:31:49: netdata ERROR : PLUGINSD[go.d] : '/usr/libexec/netdata/plugins.d/go.d.plugin' (pid 1138786) disconnected after 297762 successful data collections (ENDs).
2022-02-02 16:31:49: go.d INFO: main[main] received terminated signal (15). Terminating...
2022-02-02 16:31:54: netdata INFO  : PLUGINSD[go.d] : thread with task id 1138783 finished
```

netdata mongodb.conf:
```
jobs:
  - name: local
    uri: 'mongodb://x:x@127.0.0.1:27017/?authSource=admin'
    timeout: 20
```

Would it be possible in the mongodb plugin to be aware of the possibility that the server might go down, and try to reconnect when it comes back up. The replication stats might not be available immediately upon startup until it rejoins as a member of the replica set, so maybe that is what needs to be retried?

Worst case, netdata agent should probably restart the go.d.plugin if it disconnects like this, instead of just letting it remain dead, so I don't have to restart the agent to start it up again.

**Comment by ilyam8** [comment]
Thanks for reporting, @bompus.

> 2022-02-02 16:31:49: netdata ERROR : PLUGINSD[go.d] : requested a SET to dimension with id 'heartbeat_latency_local-1.wg0:27017' on stats 'mongodb_local.replication_heartbeat_latency' (mongodb_local.replication_heartbeat_latency) on host 'local-1', which does not exist. Disabling it.


Ok, it is not crash. There is another replication related [report](https://community.netdata.cloud/t/howto-show-mongodb-replication-charts/2402/3) - replica set metrics are not available after MongoDB restart. I started to investigate the problem. I hope will have it fixed soon.

**Comment by ilyam8** [comment]
Hi, @bompus. I think I found the problem, can you test fix #646?

**Comment by bompus** [comment]
@ilyam8 I compiled and replaced go.d.plugin from the PR branch on one server and it does appear to resolve this issue.

**Comment by ilyam8** [comment]
Big thanks for testing!
