### ISSUE TITLE
SNMP collector migration

### ISSUE THREAD

**Issue by ilyam8** [netdata/go.d.plugin#648]
The plan is to rewrite [node.d/snmp](https://github.com/netdata/netdata/tree/master/collectors/node.d.plugin/snmp) collector. The initial goal is to have the same functionality so we can deprecate nodejs version.

**Feature parity**:

 - [x] SNMP v1, v2c and v3 support.
 - [x] Multiple SNMP devices per job.
 - [x] Each SNMP device can be used to collect data for multiple charts.
 - [x] Each SNMP device will accept one or more batches to report values (can be set using `max_request_size` per SNMP server, to control the size of batches). Node.d version sends up to `max_request_size` OIDs in one SNMP GET request.
 - [x] `multiply_range` configuration option support. Node.d version dynamically creates charts for a device adding indexes from `multiply_range` to every OID. See the [Configuration](https://github.com/netdata/netdata/tree/master/collectors/node.d.plugin/snmp#configuration) section for details.

**What we need to change**: 

- configuration file format should be YAML, not JSON.
- "offset" option is not needed (not 100% sure, but that is my understanding from reading issues/checking code).

**Comment by ktsaou** [comment]
@ilyam8 auto-discovery would also be nice. But I never dived into it. I don't know how it works.

**Comment by ilyam8** [comment]
@ktsaou you are right. That is the first feature for @codeguru1 and our main goal now is to implement the same functionality first.

**Comment by ktsaou** [comment]
> @ktsaou you are right. That is the first feature for @codeguru1 and our main goal now is to implement the same functionality first.

Great! I would love to have an overview of how this works. So, once you master it, please share this knowledge (even with our users).

**Comment by ilyam8** [comment]
@codeguru1 the following can be implemented as a separate PRs, I will update the list:
 - [ ] move the initialization logic to init.go (so we call just call functions in snmp.go Init() (e.x. validateConfig())).
 - [ ] disable gosnmp library logging completely (or enable only in the debug mode)/

**Comment by codeguru1** [comment]
thanks for the testing and comments

**Comment by codeguru1** [comment]
Some PRs related to this feature, as requested by @cpipilas 
https://github.com/netdata/go.d.plugin/pull/654
https://github.com/netdata/go.d.plugin/pull/653
https://github.com/netdata/go.d.plugin/pull/644
