### ISSUE TITLE
Request to add charts to WMI plugin

### ISSUE THREAD

**Issue by cirzoltan** [netdata/go.d.plugin#666]
Hey!

I'd like to be able to monitor CPU temperature for windows machines using the WMI plugin and windows_exporter.
The key for the data I'd like to display is `windows_thermalzone_temperature_celsius` and here's how a bit of example data looks like:
```
# HELP windows_thermalzone_temperature_celsius (Temperature)
# TYPE windows_thermalzone_temperature_celsius gauge
windows_thermalzone_temperature_celsius{name="\\_TZ.THRM"} 30.05000000000001
windows_thermalzone_temperature_celsius{name="\\_TZ.TZ00"} 27.850000000000023
windows_thermalzone_temperature_celsius{name="\\_TZ.TZ01"} 29.850000000000023
```
Thanks!

**Comment by cirzoltan** [comment]
I'm mostly interested in `windows_thermalzone_temperature_celsius`.

The other ones are related to CPU throttling which I'm not that concerned with right now.

I'd just like to use this as way to keep an eye out for the temperature inside a new server cabinet with questionable airflow design choices.

**Comment by ilyam8** [comment]
@cirzoltan The PR number is 666 btw 😄 😅
