### ISSUE TITLE
[Feature request] Add MySQL Percona statistics

### ISSUE THREAD

**Issue by vobruba-martin** [netdata/go.d.plugin#676]
Percona Server for MySQL provides additional statistics. It would be great to see them in Netdata.

See https://www.percona.com/doc/percona-server/8.0/diagnostics/user_stats.html

**Comment by ilyam8** [comment]
Hi, @vobruba-martin. Can you [create a feature request](https://github.com/netdata/netdata/issues/new?assignees=&labels=feature+request%2Cneeds+triage&template=FEAT_REQUEST.yml&title=%5BFeat%5D%3A+) in the netdata/netdata repository? I plan to disable issues in this repo (will be easier for us to have issues/feature requests only in netdata/netdata).

**Comment by vobruba-martin** [comment]
Hi @ilyam8! Here it is https://github.com/netdata/netdata/issues/12705
