### ISSUE TITLE
Please add installation instructions as brew based netdata doesn't install this orchestrator

### ISSUE THREAD

**Issue by pcm32** [netdata/go.d.plugin#677]
We have a set of linux machines for which we don't have root access, but we have been allowed to install netdata through brew. However, this modality doesn't install this orchestrator. Could it be possible to get installation instructions to be able to add this orchestrator to our brew based netdata installation please? Thanks!

**Comment by ilyam8** [comment]
The brew package is not maintained by us, see https://github.com/netdata/netdata/issues/12717#issuecomment-1102883782. Closing this issue because I plan to close issues in this repo - will be using netdata/netdata.
