### ISSUE TITLE
Question: How to install custom go.d plugin with default netdata installation

### ISSUE THREAD

**Issue by nikobearrr** [netdata/go.d.plugin#687]
I have a custom plugin for netdata written in python. It is running in the python.d component.
The installation is rather simple: `cp /plugins/python.d/*/*.py /usr/libexec/netdata/python.d/`

Now, since that is the only left thing running with the python.d, I would like to rewrite it in go and remove the python.d from my netdata instance.

I have now rewritten my plugin and tested it - all looks good.

I use netdata in docker in a rather simple setup. I get the image, I copy some files to it and run it. Now I would like to do the same with the custom go.d plugin.
I would like to keep everything from netdata intact (thus not copy/paste the whole repo of go.d.plugin) and I would like to have it as a fixed version as it comes originally (as far as I know the `go.d.plugin` is released on different times/terms than `netdata` itself).

The best I have though so far:

1. In dockerfile git clone the go.d.plugin project
2. Copy my own custom plugin
3. Edit `init.go` to include my own plugin as a line
4. Run `make`
5. Copy the `godplugin` to netdata plugin folder

That is not impossible, but I do not like steps 1, 2 & 3.

Is there any other (better) way that I am missing?

**Comment by nikobearrr** [comment]
Thank you @ilyam8 I think that is a better option. Would netdata just pick it up

**Comment by ilyam8** [comment]
> Would netdata just pick it up after I put it?

You just need to make it executable and add `.plugin` suffix

```cmd
deb-work plugins.d $ ls -l | grep "plugin$"
.rwxr-x--- 1.7M root  7 Jun 15:47 apps.plugin
.rwxr-x---  20k root  7 Jun 15:47 charts.d.plugin
.rwsr-x--- 2.6M root  7 Jun 15:47 ebpf.plugin
.rwxr-x--- 5.7k root  7 Jun 15:47 fping.plugin
.rwxr-x---  29M root  9 May 21:39 go.d.plugin
.rwxr-x--- 5.4k root  7 Jun 15:47 ioping.plugin
.rwxr-x--- 1.5M root  7 Jun 15:47 perf.plugin
.rwxr-x---  25k root  7 Jun 15:47 python.d.plugin
.rwxr-x--- 1.5M root  7 Jun 15:47 slabinfo.plugin
```
