### ISSUE TITLE
powerdns X-API-KEY: failure

### ISSUE THREAD

**Issue by jostreff** [netdata/go.d.plugin#704]
When go.plugin accesses the powerdns api with "X-API-KEY:" entered the following error is seen:
  DEBUG ] build[manager] build.go:153 received config group ('/usr/local/etc/netdata/go.d/powerdns.conf'): 1 jobs (added: 1, removed: 0)
[ DEBUG ] build[manager] build.go:302 building powerdns[local] job, config: map[__provider__:file reader __source__:/usr/local/etc/netdata/go.d/powerdns.conf autodetection_retry:0 header: map[X-API-KEY:hidden] module:powerdns name:local priority:70000 update_every:1 url:http://127.0.0.1:8081/api/v1/servers/localhost/statistics]
[ ERROR ] powerdns[local] authoritativens.go:79 'http://127.0.0.1:8081/api/v1/servers/localhost/statistics' returned HTTP status code: 401
[ ERROR ] powerdns[local] job.go:169 check failed

At the same time when using command:
curl -v -H 'X-API-KEY: hidden ' http://127.0.0.1:8081/api/v1/servers/localhost/statistics
error 401 none.

Any advices are welcome - for me it looks that X-API-KEY is not send correctly to powerdns server.

**Comment by jostreff** [comment]
version netdata-go-0.33.0

**Comment by ilyam8** [comment]
Hi, @jostreff. I think it is **headers**, not **header**.

**Comment by jostreff** [comment]
This was exactly my problem - changing quickly config from python.d to go.d.
Thanks!
