### ISSUE TITLE
web_log extensive testing/optimization

### ISSUE THREAD

**Issue by ilyam8** [netdata/go.d.plugin#88]
hpcloud/tail consumes a lot of cpu, shouldn't be used

**Comment by Wing924** [comment]
hpcloud/tail  looks slow, we need fsnotify.
cf. https://github.com/grafana/loki/blob/68e1a049a0/pkg/promtail/targets/filetarget.go

**Comment by Wing924** [comment]
not easy as it looks

**Comment by ilyam8** [comment]
i'd say it doesn't look easy.
